In [36]:
import pandas as pd

Creating a dataframe from Fineli dataset

In [37]:
fineli_data = pd.read_csv("resultset.csv", sep=";")

In [38]:
fineli_data.head()

,id,name,"energia, laskennallinen (kJ)",rasva (g),hiilihydraatti imeytyvä (g),proteiini (g),alkoholi (g),orgaaniset hapot (g),sokerialkoholi (g),sokerit (g),...,pyridoksiini vitameerit (vetykloridi) (B6) (mg),riboflaviini (B2) (mg),tiamiini (B1) (mg),A-vitamiini RAE (µg),karotenoidit (µg),B12-vitamiini (kobalamiini) (µg),C-vitamiini (mg),D-vitamiini (µg),E-vitamiini alfatokoferoli (mg),K-vitamiini (µg)
0,812,Ahven,345,0.7,0,18.8,0,0,0.0,0,...,0.22,0.07,0.07,6.4,0,1.9,0,15.2,1.5,0.80
1,8009,"Ahven, leivitetty, paistettu",660,6.5,4.7,19.9,0,<0.1,0.0,<0.1,...,0.23,0.06,0.06,28.0,6.3,1.6,<0.1,15.8,2.5,6.81
2,32229,"Ahven, paistettu, ei korppujauhoja",600,6.8,<0.1,20.5,0,<0.1,0.0,<0.1,...,0.24,0.07,0.05,29.9,6.4,1.8,<0.1,16.8,2.7,7.21
3,32230,"Ahven, paistettu voissa, ei korppujauhoja",595,7.3,<0.1,19.1,0,0,0.0,<0.1,...,0.22,0.06,0.05,62.9,36.9,1.6,0,15.3,1.6,2.29
4,29011,"Ahvenet foliossa, voissa",496,4.1,0.6,19.5,0,<0.1,0.0,0.6,...,0.25,0.07,0.06,40.2,127.6,1.6,1.7,15.5,1.6,7.16

Creating another dataframe

In [39]:
names_for_korp = fineli_data.copy()
names_for_korp = names_for_korp[["name"]]

In [40]:
names_for_korp.head()

                                        name
0                                      Ahven
1               Ahven, leivitetty, paistettu
2         Ahven, paistettu, ei korppujauhoja
3  Ahven, paistettu voissa, ei korppujauhoja
4                   Ahvenet foliossa, voissa

Cleaning food names, removing spaces and duplicates

In [41]:
names_for_korp = [x.lower().split(",")[0].split(" ")[0] for x in names_for_korp["name"]]

names_for_korp = list(dict.fromkeys(names_for_korp))

In [42]:
print(names_for_korp)

['ahven', 'ahvenet', 'amarantti', 'ananas', 'ananassalsa', 'anjovis', 'ankerias', 'appelsiini', 'appelsiinimarmeladi', 'appelsiiniriisi', 'aprikoosi', 'aprikoosi-riisipuuro', 'aprikoosisose', 'aromiruismallas', 'aromisuola/yrttisuola', 'ateria-ainekset', 'ateriakastike', 'ateriankorvike', 'ateriasalaatti', 'auringonkukansiemen', 'auringonkukkaöljy', 'avokado', 'avokadopasta', 'avokado-quesadilla', 'avokadoöljy', 'bambunverso', 'banaani', 'banaanilastu', 'banaanipannukakku', 'basilika', 'bataatti', 'bataatti-kikhernecurry', 'bataatti-kookoskeitto', 'bataattiranskalainen', 'bataattisose', 'bataattisosekeitto', 'bearnaisekastike', 'bearnaisekastikejauhe', 'blini', 'bloody', 'bolognan', 'booli', 'borssikeitto', 'broileri', 'broileria', 'broilerifilee', 'broilerifileesuikale', 'broilerikastike', 'broileri-kasviswokki', 'broilerikeitto', 'broilerimureke', 'broilerinleike', 'broilerin', 'broilerinuggetti', 'broileri-nuudeliwokki', 'broileri-pastakeitto', 'broileri-pastavuoka', 'broileripata', 'broileripiirakka', 'broileripyörykkä', 'broilerisuikale', 'broilerpasta', 'broiler-pekonipasta', 'canneloni', 'cashewpähkinäjuoma', 'chapati', 'chiansiemen', 'chili', 'chorizo', 'creme', 'dippikastikejauhe', 'donitsi', 'dry', 'eksoottinen', 'elovena', 'energiajuoma', 'erikoishedelmä', 'etana', 'etikkakurkku', 'etikkapunajuuri', 'etikkasienisäilyke', 'fenkoli', 'fenkolikeitto', 'feta-kasvispannu', 'feta-kasvispihvi', 'feta-pinaattikastike', 'feta-pinaattipiirakka', 'fruktoosi', 'gin', 'glögijuoma', 'graavilohi', 'graham-marjapuuro', 'grahampuuro', 'grahamvelli', 'granaattiomena', 'greippi', 'grillimakkara', 'grillivartaat', 'guava', 'haaparousku', 'halva', 'hampunsiemen', 'hampurilainen', 'hapanimeläbroileri', 'hapankaali', 'hapankaalikeitto', 'hapankorppu', 'hapankurkku', 'hapanlohko', 'hasselpähkinäjuoma', 'hauki', 'hedelmä', 'hedelmähillo', 'hedelmähyytelö', 'hedelmäjuoma', 'hedelmäpastilli', 'hedelmäsalaatti', 'hedelmäsalaattisäilyke', 'hedelmäsose', 'herajauhe', 'heraproteiinikonsentraatti', 'herkkusieni', 'herkkusienikeitto', 'herkkusienimuhennos', 'herkkutatti', 'herne', 'herneenverso', 'hernekeitto', 'hernemuhennos', 'hernesosekeitto', 'hiiva', 'hillo', 'hillopiirakka', 'hillosipulisäilyke', 'hirssi', 'hirssipihvi', 'hirssipuuro', 'hirssivelli', 'hirvenliha', 'hirvenlihakastike', 'hirvenlihakeitto', 'hirvenlihakäristys', 'hirvenpaisti', 'hoki', 'hollandaisekastike', 'hollandaisekastikejauhe', 'homburgin', 'hummeri', 'hummus', 'hunaja', 'hunajameloni', 'hunaja-omena-viinietikka', 'härkis', 'härkiskastike', 'härkis-kasviswokki', 'härkis-nuudeliwokki', 'härkispihvi', 'härkäruukku', 'häränlihahöystö', 'inkivääri', 'irish', 'italianpata', 'itu', 'jauheliha', 'jauhelihaa', 'jauhelihakastike', 'jauheliha-kasvispata', 'jauhelihakeitto', 'jauheliha-linssikeitto', 'jauheliha-makaronimuhennos', 'jauheliha-nachopaistos', 'jauheliha-pastakeitto', 'jauhelihapihvi', 'jauheliha-punajuurivuoka', 'jauheliha-riisipata', 'jauhemaksapihvi', 'jauho', 'jogurtti', 'jogurttirusina/jogurttihedelmä', 'johanneksenleipäpuujauhe', 'joulutorttu', 'juolukka', 'juurekset', 'juurespatee', 'juuressosekeitto', 'juuressurvos', 'juuriselleri', 'juusto', 'juustofondue', 'juustoinen', 'juusto-kasviskeitto', 'juustokeitto', 'juustokohokas', 'juustonaksu', 'juustopiirakka', 'juustoröstiperuna', 'juustosarvi', 'juustosilakat', 'juustotikku', 'jälkiruoka', 'jälkiruokakastike', 'jänis', 'jäädyke', 'jääsalaatti', 'jäätelö', 'jäävuorisalaatti', 'kaakaojauhe', 'kaakaojuoma', 'kaakaorasva', 'kaali', 'kaalikeitto', 'kaalikääryle', 'kaalilaatikko', 'kaalipata', 'kaali-perunakeitto', 'kaalipihvi', 'kaalipiirakka', 'kahvi', 'kahvijuoma', 'kakku', 'kakku-', 'kakkukreemi', 'kakkurasva', 'kakun', 'kala', 'kala-juurespata', 'kalakastike', 'kala-kasviskeitto', 'kala-kasvispaistos', 'kala-kasvispata', 'kala-kasvissose', 'kala-katkarapuvuoka', 'kalakeitto', 'kalakukko', 'kalalevite', 'kalaliemi', 'kalaliemikuutio', 'kalamureke', 'kalapaistos', 'kalapasteija', 'kala-perunapata', 'kalapiirakka', 'kala-pinaattivuoka', 'kalapuikko', 'kalapyörykkä', 'kala-riisilaatikko', 'kala-riisipiirakka', 'kalja', 'kalja-', 'kalkkuna', 'kalkkunakastike', 'kalkkuna-kasviswokki', 'kalkkunaleike', 'kalkkunan', 'kampanisu', 'kampela', 'kampelafilee', 'kana', 'kanakastike', 'kana-kasvissose', 'kanakeitto', 'kanaliemi', 'kanaliemikuutio', 'kananmuna', 'kananmunajauhe', 'kananmunan', 'kanapata', 'kanapyörykkä/broileripyörykkä', 'kanaviillokki', 'kana-vuohenjuustopasta', 'kangasrousku', 'kangastatti', 'kani', 'kantarelli', 'karjalanpiirakka', 'karpalo', 'karppisokeri', 'karvarousku', 'karviainen', 'kasslerpaisti', 'kasslerpihvi', 'kasslerpihvi/-paisti', 'kastanja', 'kastike', 'kastikejauhe', 'kasvirasvalevite', 'kasvis', 'kasvisgratiini', 'kasviskaalikääryle', 'kasviskastike', 'kasviskeitto', 'kasviskuskus', 'kasvislevite', 'kasvisliemi', 'kasvisliemikuutio', 'kasvisminestronekeitto', 'kasvispihvi', 'kasvispihvi/pyörykkä', 'kasvispiirakka', 'kasvispyörykkä', 'kasvis-sienipiirakka', 'kasvissose', 'kasvissosekeitto', 'kasviöljyvalmiste', 'katajanmarja', 'katkarapu', 'katkarapukeitto', 'katkarapumuhennos', 'katkarapu-nuudeliwokki', 'katkarapu-porkkanakeitto', 'kaurahiutale', 'kaurajuoma', 'kaurakuitunen', 'kauramakaroni', 'kaurapuuro', 'kaura-ruispuuro', 'kauravalmiste', 'kauravelli', 'kaviaari', 'kebab', 'kebableipä', 'kebabliha', 'kebakko', 'keitinpiirakka', 'keksi', 'keltuaisjauhe', 'kerma', 'kermainen', 'kermakastike', 'kermalikööri', 'kermaperuna', 'kermavaahto', 'kermavaahtospray', 'kermaviili', 'kesäkeitto', 'kesäkurpitsa', 'ketsuppi', 'kevätkääryle', 'kieli', 'kiinankaali', 'kiisseli', 'kiivi', 'kikherne', 'kikherne-perunapata', 'kikhernepyörykkä', 'kilohaili', 'kinder', 'kinkku-ananaspasta', 'kinkku-juustopiirakka', 'kinkkukastike', 'kinkkupasta', 'kinkku-pekoniruukku', 'kinkkupiirakka', 'kirjolohi', 'kirjolohifilee', 'kirsikka', 'kivennäisvesi', 'kokolihaleikkele', 'konjakki/rommi/viski', 'kookoshiutale', 'kookosjuoma', 'kookosmaito', 'kookosrasva', 'kookosvesi', 'kookosöljy', 'korianteri', 'korppu', 'korvasieni', 'korvasienikeitto', 'kreemi', 'kruskapuuro', 'krutonki', 'ksylitolipastilli', 'ksylitolipurukumi', 'kuha', 'kuivakakku', 'kukkakaali', 'kukkakaalimuhennos', 'kukkakaalisosekeitto', 'kuorrutuskastike', 'kurkku', 'kurkkukeitto', 'kurpitsa', 'kurpitsakeitto', 'kurpitsamuhennos', 'kurpitsansiemen', 'kuskus', 'kuusenkerkkä', 'kvinoa', 'kvinoarisotto', 'kylmä', 'kyssäkaali', 'kyssäkaalimuhennos', 'kääretorttu', 'kääretortun/täytekakun', 'kääretortun', 'köyhät', 'lahna', 'lakka', 'lakritsi', 'lampaan-', 'lampaankyljys', 'lampaankääpä', 'lampaanliha', 'lampaanliharulla', 'lampaanpaisti', 'lampaanpihvi', 'lanttu', 'lanttukukko', 'lanttulaatikko', 'lanttupiirakka', 'lanttusurvos', 'lasagne', 'latva-artisokka', 'lauantaimakkara', 'lehtikaali', 'lehtikaalisipsit', 'lehtisalaatti', 'lehtiselleri', 'leikkelemakkara', 'leipomoteollisuusmargariini', 'leipäpuuro', 'leipärasva', 'leivinjauhe', 'leivontamargariini', 'lenkkimakkara', 'lese', 'liha', 'lihahyytelö', 'lihakastike', 'liha-kasvispata', 'lihakeitto', 'lihakukko', 'lihakääryle', 'lihaliemi', 'lihaliemijauhe/tiiviste', 'lihamureke', 'lihapata', 'lihapiirakka', 'lihapulla', 'lihapullat', 'liha-riisipasteija', 'liha-sienimureke', 'lihasäilyke', 'liivate', 'likööri', 'lindströminpihvi', 'linssi', 'linssikeitto', 'linssipihvi/pyörykkä', 'lipeäkala', 'lohi', 'lohifilee', 'lohimurekepihvi', 'lohipasta', 'lohipiirakka', 'lohi-riisipiirakka', 'lohkoperuna', 'luumu', 'luumu-kaurapuuro', 'luumukeitto', 'luumu-kermahyytelö', 'luumukohokas', 'luumumarmeladi', 'luumu-riisijälkiruoka', 'maa-artisokka', 'maa-artisokkakeitto', 'maapähkinälevite', 'maapähkinäöljy', 'made', 'maissi', 'maissilastu', 'maissinaksu', 'maissinjyvä', 'maissintähkä', 'maissipuuro', 'maissitortilla', 'maissivelli', 'maissiöljy', 'maito', 'maitohorsma', 'maitojauhe', 'maitokastike', 'maitoperuna', 'maizena', 'majoneesi', 'makaroni', 'makaronilaatikko', 'makaronipuuro', 'makaronivelli', 'makean', 'makeinen', 'makeutusaine', 'makkara', 'makkarakastike', 'makkarakeitto', 'makkarapata', 'makkaraperunat', 'makrilli', 'maksa', 'maksakastike', 'maksalaatikko', 'maksamakkara', 'maksapaisti', 'maksapasteija', 'maksapata', 'maksapihvi', 'maltodekstriini', 'mandariini', 'mango', 'mango-chutney', 'mangoldi', 'mannapuuro', 'mannasuurimo', 'mannavelli', 'mansikka', 'mansikkahillo', 'mansikkasurvos', 'manteli', 'mantelijuoma', 'mantelikala', 'marenki', 'margariini', 'marja', 'marja-aronia', 'marjahillo', 'marjahyytelö', 'marjajuoma', 'marjamaito', 'marjapiirakka', 'marjapiirakka/marjapaistos', 'marja-raparperipiirakka', 'marjasose', 'marjatalkkuna', 'marjavaahto', 'marmeladi', 'marsipaani', 'maustekastike', 'maustekurkku', 'maustetahna', 'meetvursti', 'mehu', 'mehuhyytelö', 'mehujuomatiiviste', 'mehujää', 'meloni', 'merilevä', 'merisuola', 'metsälintu', 'mieto', 'mifu', 'mineraalisuola', 'minestronekeitto', 'misokeitto', 'moniviljapuuro', 'moussaka', 'muikku', 'muikkusäilyke', 'muksu', 'munakas', 'munakasrulla', 'munakastike', 'muna-kinkkuvuoka', 'munakoiso', 'munakoisonyytti', 'munakokkeli', 'muna-riisipasteija', 'munatoti', 'munavelli', 'munavoi', 'munkinpaistorasva', 'munkki', 'munkki/donitsi', 'munuainen', 'munuaiskastike', 'muro', 'mustaherukanlehtiuute', 'mustaherukka', 'mustajuuri', 'mustajuurimuhennos', 'mustajuurisosekeitto', 'mustapippuri', 'mustatorvisieni', 'mustekala', 'mustikka', 'mustikkahyve', 'mustikkasurvos', 'mysli', 'mämmi', 'männynherkkutatti', 'mäti', 'mätikastike', 'mätitahna', 'nahkiainen', 'nakki', 'nakkikastike', 'nakkikeitto', 'nakki-sekavihannesvuoka', 'nakkistroganoff', 'nakkisämpylä', 'nalle', 'naudan/vasikankyljys', 'naudanfilee', 'naudankylki', 'naudanlapa/etuselkä', 'naudanliha', 'naudanliha-kasvissose', 'naudanlihaleike', 'naudanliha-nuudeliwokki', 'naudanliha-pastakeitto', 'naudanliha-perunasose', 'naudanlihapihvi', 'naudanlihasuikale', 'naudanliha-tofu-nuudeliwokki', 'naudanpaisti', 'naudanpaisti-kasviswokki', 'naudanpotka', 'naudanrinta', 'naudanruho', 'nauris', 'neljän', 'neljänviljanpuuro', 'neljänviljanvelli', 'nokkonen', 'nokkoskeitto', 'nokkosmuhennos', 'nokkosohukainen', 'nuppuvihannes', 'nuudeli', 'nuudelikeitto', 'nuudeli-tofukeitto', 'nyhtökaura', 'nyhtökaura-nuudeliwokki', 'nyhtöpossu', 'näkkileipä', 'ohrahiutale', 'ohrapuuro', 'ohrasuurimo', 'ohratärkkelys', 'ohravelli', 'ohukainen', 'oliivi', 'oliiviöljy', 'olut', 'omena', 'omenahillo', 'omena-kaurahiutalepaistos', 'omenalastu', 'omenapiirakka', 'omena-rahkapiirakka', 'omena-riisipuuro', 'omenasose', 'oregano', 'osteri', 'osterikeitto', 'osterivinokas', 'paahtoleipä', 'paella', 'paistinkastike', 'paistinrasva', 'paistoöljy', 'pakastekasvissekoitus', 'palmuydinöljy', 'palmuöljy', 'palsternakka', 'palsternakkamuhennos', 'palsternakka-omenakeitto', 'panang', 'pangasius', 'pannukakku', 'papadum', 'papaija', 'pappilan', 'paprika', 'paprikajauhe', 'papu', 'papukeitto', 'papu-kesäkurpitsakeitto', 'papu-kvinoapihvi/pyörykkä', 'papumuhennos', 'papupata', 'papupihvi/pyörykkä', 'parsa', 'parsakaali', 'parsakaalimuhennos', 'parsakeitto', 'pasha', 'passionhedelmä', 'pasta', 'pastakastike', 'pasta-vihanneskeitto', 'pasteija', 'patakukko', 'pekoni', 'pellavansiemen', 'pellavansiemenrouhe', 'pellavaöljy', 'persikka', 'persikka/nektariini', 'persilja', 'peruna', 'perunahiutale', 'peruna-kasvispata', 'perunakroketti', 'peruna-kukkakaalicurry', 'perunakukko', 'perunalaatikko', 'perunalastu', 'perunamoussaka', 'perunaohukainen', 'perunapaistos', 'peruna-parsakaalisosekeitto', 'perunapihvi/pyörykkä', 'perunapiirakka', 'peruna-pinaattisose', 'peruna-porkkanasose', 'perunapuuro', 'perunaruusu', 'peruna-sipulilaatikko', 'perunasose', 'perunasosejauhe', 'perunavelli', 'perunavoitaikina', 'pestokastike', 'pihlajanmarja', 'piimä', 'piimävelli', 'piirakan', 'pikkuleipärasva', 'pilahviriisi', 'pinaatti', 'pinaattikeitto', 'pinaattikohokas', 'pinaattimuhennos', 'pinaatti-munalaatikko', 'pinaattiohukainen', 'pinaatti-riisilaatikko', 'pinjansiemen', 'piparjuuri', 'piparkakkutaikina', 'pirtelö', 'pizza', 'pizzapohja', 'popcorn', 'porilainen', 'porkkana', 'porkkanalaatikko', 'porkkanamuhennos', 'porkkanaohukainen', 'porkkana-perunasose', 'porkkanapiirakka', 'porkkana-riisipiirakka', 'porkkanasosekeitto', 'porkkanasurvos', 'poro-juustopiirakka', 'poro-kantarellipiirakka', 'porokeitto', 'poronkäristys', 'poronliha', 'poronlihamureke', 'poronmaksapihvi', 'poronpaisti', 'poro-rieskarulla', 'porsaanfilee', 'porsaankyljys', 'porsaankylki', 'porsaanleike', 'porsaanliha-kasvissose', 'porsaanliha-perunasose', 'porsaannuggetti', 'porsaanpaisti', 'porsas-kasviswokki', 'possupaisti', 'profeel', 'psyllium', 'pulla', 'pulla-', 'puna-ahven', 'punaherukka', 'punainen', 'punaista', 'punajuuri', 'punajuuri-fetamunakas', 'punajuurikeitto', 'punajuuripestokastike', 'punajuuripihvi', 'punajuuri-riisilaatikko', 'punajuuri-sinihomejuustovuoka', 'punajuuri-vuohenjuustopiirakka', 'punajuuri-vuohenjuustovuoka', 'punakaali', 'punakaalimuhennos', 'punasalaatti', 'punasipuli', 'punaviini', 'punaviinikastike', 'punikkitatti', 'puolukka', 'puolukkahillo', 'puolukkarönttönen', 'puolukkasurvos', 'purjo', 'purjo-perunasosekeitto', 'purjosipuli', 'purukumi', 'pussikeitto', 'pyttipannu', 'pähkinä', 'pähkinä-hedelmä-sekoitus', 'pähkinämureke/pyörykkä', 'pähkinäsekoitus', 'pähkinävälipala', 'päärynä', 'quorn', 'quorn-tomaattikastike', 'raakamakkara', 'raejuusto', 'raejuusto-munavoi', 'rahka', 'rahkajuoma', 'rahkamarjapiirakka', 'rahkapiirakan', 'rahkapiirakka', 'rahkavoitaikina', 'ranskanperuna', 'ranskanperunavalmiste', 'raparperi', 'raparperi-kaurahiutalepaistos', 'raparperipiirakka', 'raparperirahkapiirakka', 'raparperi-riisipuuro', 'rapu', 'rasvajauhe', 'rasvaseos', 'rasvaseoslevite', 'ratatouille', 'retiisi', 'riimiliha', 'riisi', 'riisijuoma', 'riisikakku', 'riisi-kauraseos', 'riisi-kermajälkiruokapohja', 'riisi-kvinoa-moniviljaseos', 'riisi-maissikakku', 'riisi-ohraseos', 'riisipuuro', 'riisipyörönen', 'riisi-ruisseos', 'riisisuklaa', 'riisitärkkelys', 'riisivalmiste', 'riisivelli', 'riista', 'risotto', 'rommikola', 'roomansalaatti', 'rosolli', 'rouhe', 'ruishiutale', 'ruisleipä', 'ruismallas', 'ruis-marjapuuro', 'ruis-perunapuuro', 'ruispuuro', 'ruis-riisiseos', 'ruissipsi', 'ruis-vehnä-perunataikina', 'ruisvelli', 'rukola', 'runebergintorttu', 'ruoanvalmistuskerma', 'ruoanvalmistusrasva', 'ruohosipuli', 'ruokasooda', 'ruokasuola', 'ruokaöljy', 'rusina', 'ruskea', 'ruusukaali', 'ruusukaalikeitto', 'ruusunmarja', 'ruusunmarjasose', 'rypsiporsas', 'rypsiöljy', 'rypälesokeri', 'ryynimakkara', 'rössymaito', 'rössypottu', 'röstiperuna', 'salaatinkastike', 'salaatti', 'sardiini', 'savuporo-juustokeitto', 'savuporokeitto', 'screwdriver', 'seesaminsiemen', 'seesaminuggetti', 'seiti', 'sekahedelmä', 'sekaleipä', 'sekavihannes', 'sekavihannesmuhennos', 'sellerimuhennos', 'sharon', 'siankinkku', 'siankyljys', 'siankyljys/selkä', 'siankylki', 'siankärsämö', 'sianlapa', 'sianliha', 'sianlihasuikale', 'sian', 'sianpaisti', 'sianpotka', 'sianpotka/sorkka', 'sianruho', 'siemensekoitus', 'sieni', 'sieni-juurespata', 'sieni-kaalikääryle', 'sienikastike', 'sienikastike/muhennos', 'sieni-kasvismuhennos', 'sienikeitto', 'sieni-ohrakeitto', 'sieni-ohrasuurimolaatikko', 'sieniohukainen', 'sienipihvi/pyörykkä', 'sienipiirakka', 'sieni-sipulihakkelus', 'siideri', 'siiderijuoma', 'siika', 'siirappi', 'siitakesieni', 'silakka', 'silakkafilee', 'silakkahyytelö', 'silli', 'sima', 'simpukkakastike', 'simpukkakeitto', 'sinappi', 'sinihomejuustokastike', 'sinipallas', 'sinisimpukka', 'sipuli', 'sipulikeitto', 'sipulimuhennos', 'sipulipiirakka', 'sipulirengas', 'siskonmakkarakeitto', 'sitruuna', 'sitruunakastike', 'sitruunavaahto', 'skyr', 'smetana', 'smetanalohi', 'smoothie', 'soijajuoma', 'soija-kasviskastike', 'soija-kasviskiusaus', 'soija-marja-pellava-ruis-jauheseos', 'soijanakkikastike', 'soijanakkikeitto', 'soijanakkistroganoff', 'soijapapu', 'soijapihvi', 'soijaproteiini', 'soijarouhe', 'soija-ruusunmarja-pellava-inuliinivalmiste', 'soija-ruusunmarja-pellava-valmiste', 'soijavalmiste', 'soijavälipala', 'soijaöljy', 'sokeri', 'sokeririnkeli', 'sokerivesikuorrutus', 'sorbetti', 'sorbitoli', 'spagetti', 'spagettikastikejauhe', 'spagettilihavuoka', 'suklaa', 'suklaakonvehti', 'suklaapatukka', 'suklaa-pähkinälevite', 'suklaarusina', 'sulatejuusto', 'sultsina', 'suolapähkinä-hedelmä-sekoitus', 'suolatikku', 'suppilovahvero', 'suppilovahverokeitto', 'sushi', 'sydän', 'syrnikki', 'särki', 'taateli', 'tahini', 'taimen', 'tali', 'talkkunapiimä', 'talkkunapuuro', 'tapas', 'tartarpihvi', 'tattari', 'tattaripuuro', 'tattarivelli', 'tee', 'tempeh', 'teollisuusmargariini', 'teriyaki-kanaa', 'ternimaito', 'tikka', 'tilapia', 'tilli', 'tillikastike', 'timjami', 'tippaleipä', 'tofu', 'tofu-kasviskastike', 'tofu-kasviswokki', 'tofu-nuudeliwokki', 'tofu-papukastike', 'tofu-perunavuoka', 'tofupihvi', 'tomaatti', 'tomaattikastike', 'tomaattikeitto', 'tomaatti-mozzarellapasta', 'tomaatti-mozzarellapiirakka', 'tomaattimurska', 'tomaattisalsa', 'tomaattisilakka', 'tomaattisose', 'tom', 'tonikki', 'tonnikala', 'tonnikala-makaronimuhennos', 'tonnikalapasta', 'tonnikalapihvi', 'torttupohja', 'tuontikala', 'tuorejuusto', 'tuoremehucampari', 'tuorepuuro', 'turska', 'tuulihattu', 'tyrnimarja', 'tärkkelyssiirappi', 'täysjyväriisi', 'täysksylitolipastilli', 'täysmehu', 'täytekakku', 'täytekakun/kääretortun', 'täytekakun', 'täytetty', 'unelmatortun', 'unikonsiemen', 'urheilujuoma', 'urheilujuomatiiviste', 'uunibanaani', 'uunihauki', 'uunijuurekset', 'uunikala', 'uuniomena', 'uuniperuna', 'uunisilakka', 'uunivihannekset', 'vaalea', 'vadelma', 'vadelmasurvos', 'valkokaali', 'valkopippuri', 'valkoretikka', 'valkosipuli', 'valkosipulietana', 'valkosipuliperuna', 'valkoviini', 'valkuaisjauhe', 'vanilliinisokeri', 'vanukas', 'variksenmarja', 'vasikanpaisti', 'vasikanpotka', 'vatruska', 'vehnähiutale', 'vehnänalkio', 'vehnäpuuro', 'vehnätortilla', 'vehnävelli', 'veri', 'verigreippi', 'verileipä', 'veriohukainen', 'vesi', 'vesikastanja', 'vesimeloni', 'vesirinkeli', 'wieninleike', 'vihanneskeitto', 'vihanneskrassi', 'vihannesmunavuoka', 'viikuna', 'viili', 'viina', 'viineri', 'viini', 'viinietikka', 'viiniglögi', 'viininlehti', 'viininlehtikääryle', 'viinirypäle', 'viiriäisen', 'viljaporsas', 'villirucola', 'virkistysjuoma', 'virvoitusjuoma', 'vitamiinivesi', 'vohveli', 'vohvelikuori', 'voi', 'voikreemitäyte', 'voikukka', 'voileipä', 'voileipäkakku', 'voileipäpikkelssi', 'voirinkeli', 'voisarvi', 'voitaikina', 'voitaikinarasva', 'voiöljy', 'wokatut', 'wok-kasvikset', 'vorschmack', 'vuohenputki', 'vuonankaali', 'väinönputki', 'väkevä', 'väkiviinaetikka', 'välipalajuoma', 'välipalapatukka', 'yrtti', 'yrttilevite', 'äidinmaidonkorvike', 'äidinmaito']

Creating smaller sublists so that the Korp search does not crash

In [43]:
names_for_korp1 = names_for_korp[0:150]
names_for_korp2 = names_for_korp[150:301]
names_for_korp3 = names_for_korp[301:451]
names_for_korp4 = names_for_korp[451:601]
names_for_korp5 = names_for_korp[601:751]
names_for_korp6 = names_for_korp[751:901]
names_for_korp7 = names_for_korp[901:1051]
names_for_korp8 = names_for_korp[1051:]

Modifying lists into Korp's CQP form

In [44]:
CQP_search1 = " | ".join([f"\"{n}\"" for n in names_for_korp1])
CQP_search2 = " | ".join([f"\"{n}\"" for n in names_for_korp2])
CQP_search3 = " | ".join([f"\"{n}\"" for n in names_for_korp3])
CQP_search4 = " | ".join([f"\"{n}\"" for n in names_for_korp4])
CQP_search5 = " | ".join([f"\"{n}\"" for n in names_for_korp5])
CQP_search6 = " | ".join([f"\"{n}\"" for n in names_for_korp6])
CQP_search7 = " | ".join([f"\"{n}\"" for n in names_for_korp7])
CQP_search8 = " | ".join([f"\"{n}\"" for n in names_for_korp8])

Printing each list for copying and pasting into Korp

In [45]:
print(CQP_search1)

"ahven" | "ahvenet" | "amarantti" | "ananas" | "ananassalsa" | "anjovis" | "ankerias" | "appelsiini" | "appelsiinimarmeladi" | "appelsiiniriisi" | "aprikoosi" | "aprikoosi-riisipuuro" | "aprikoosisose" | "aromiruismallas" | "aromisuola/yrttisuola" | "ateria-ainekset" | "ateriakastike" | "ateriankorvike" | "ateriasalaatti" | "auringonkukansiemen" | "auringonkukkaöljy" | "avokado" | "avokadopasta" | "avokado-quesadilla" | "avokadoöljy" | "bambunverso" | "banaani" | "banaanilastu" | "banaanipannukakku" | "basilika" | "bataatti" | "bataatti-kikhernecurry" | "bataatti-kookoskeitto" | "bataattiranskalainen" | "bataattisose" | "bataattisosekeitto" | "bearnaisekastike" | "bearnaisekastikejauhe" | "blini" | "bloody" | "bolognan" | "booli" | "borssikeitto" | "broileri" | "broileria" | "broilerifilee" | "broilerifileesuikale" | "broilerikastike" | "broileri-kasviswokki" | "broilerikeitto" | "broilerimureke" | "broilerinleike" | "broilerin" | "broilerinuggetti" | "broileri-nuudeliwokki" | "broileri-pastakeitto" | "broileri-pastavuoka" | "broileripata" | "broileripiirakka" | "broileripyörykkä" | "broilerisuikale" | "broilerpasta" | "broiler-pekonipasta" | "canneloni" | "cashewpähkinäjuoma" | "chapati" | "chiansiemen" | "chili" | "chorizo" | "creme" | "dippikastikejauhe" | "donitsi" | "dry" | "eksoottinen" | "elovena" | "energiajuoma" | "erikoishedelmä" | "etana" | "etikkakurkku" | "etikkapunajuuri" | "etikkasienisäilyke" | "fenkoli" | "fenkolikeitto" | "feta-kasvispannu" | "feta-kasvispihvi" | "feta-pinaattikastike" | "feta-pinaattipiirakka" | "fruktoosi" | "gin" | "glögijuoma" | "graavilohi" | "graham-marjapuuro" | "grahampuuro" | "grahamvelli" | "granaattiomena" | "greippi" | "grillimakkara" | "grillivartaat" | "guava" | "haaparousku" | "halva" | "hampunsiemen" | "hampurilainen" | "hapanimeläbroileri" | "hapankaali" | "hapankaalikeitto" | "hapankorppu" | "hapankurkku" | "hapanlohko" | "hasselpähkinäjuoma" | "hauki" | "hedelmä" | "hedelmähillo" | "hedelmähyytelö" | "hedelmäjuoma" | "hedelmäpastilli" | "hedelmäsalaatti" | "hedelmäsalaattisäilyke" | "hedelmäsose" | "herajauhe" | "heraproteiinikonsentraatti" | "herkkusieni" | "herkkusienikeitto" | "herkkusienimuhennos" | "herkkutatti" | "herne" | "herneenverso" | "hernekeitto" | "hernemuhennos" | "hernesosekeitto" | "hiiva" | "hillo" | "hillopiirakka" | "hillosipulisäilyke" | "hirssi" | "hirssipihvi" | "hirssipuuro" | "hirssivelli" | "hirvenliha" | "hirvenlihakastike" | "hirvenlihakeitto" | "hirvenlihakäristys" | "hirvenpaisti" | "hoki" | "hollandaisekastike" | "hollandaisekastikejauhe" | "homburgin" | "hummeri" | "hummus" | "hunaja"

In [46]:
print(CQP_search2)

"hunajameloni" | "hunaja-omena-viinietikka" | "härkis" | "härkiskastike" | "härkis-kasviswokki" | "härkis-nuudeliwokki" | "härkispihvi" | "härkäruukku" | "häränlihahöystö" | "inkivääri" | "irish" | "italianpata" | "itu" | "jauheliha" | "jauhelihaa" | "jauhelihakastike" | "jauheliha-kasvispata" | "jauhelihakeitto" | "jauheliha-linssikeitto" | "jauheliha-makaronimuhennos" | "jauheliha-nachopaistos" | "jauheliha-pastakeitto" | "jauhelihapihvi" | "jauheliha-punajuurivuoka" | "jauheliha-riisipata" | "jauhemaksapihvi" | "jauho" | "jogurtti" | "jogurttirusina/jogurttihedelmä" | "johanneksenleipäpuujauhe" | "joulutorttu" | "juolukka" | "juurekset" | "juurespatee" | "juuressosekeitto" | "juuressurvos" | "juuriselleri" | "juusto" | "juustofondue" | "juustoinen" | "juusto-kasviskeitto" | "juustokeitto" | "juustokohokas" | "juustonaksu" | "juustopiirakka" | "juustoröstiperuna" | "juustosarvi" | "juustosilakat" | "juustotikku" | "jälkiruoka" | "jälkiruokakastike" | "jänis" | "jäädyke" | "jääsalaatti" | "jäätelö" | "jäävuorisalaatti" | "kaakaojauhe" | "kaakaojuoma" | "kaakaorasva" | "kaali" | "kaalikeitto" | "kaalikääryle" | "kaalilaatikko" | "kaalipata" | "kaali-perunakeitto" | "kaalipihvi" | "kaalipiirakka" | "kahvi" | "kahvijuoma" | "kakku" | "kakku-" | "kakkukreemi" | "kakkurasva" | "kakun" | "kala" | "kala-juurespata" | "kalakastike" | "kala-kasviskeitto" | "kala-kasvispaistos" | "kala-kasvispata" | "kala-kasvissose" | "kala-katkarapuvuoka" | "kalakeitto" | "kalakukko" | "kalalevite" | "kalaliemi" | "kalaliemikuutio" | "kalamureke" | "kalapaistos" | "kalapasteija" | "kala-perunapata" | "kalapiirakka" | "kala-pinaattivuoka" | "kalapuikko" | "kalapyörykkä" | "kala-riisilaatikko" | "kala-riisipiirakka" | "kalja" | "kalja-" | "kalkkuna" | "kalkkunakastike" | "kalkkuna-kasviswokki" | "kalkkunaleike" | "kalkkunan" | "kampanisu" | "kampela" | "kampelafilee" | "kana" | "kanakastike" | "kana-kasvissose" | "kanakeitto" | "kanaliemi" | "kanaliemikuutio" | "kananmuna" | "kananmunajauhe" | "kananmunan" | "kanapata" | "kanapyörykkä/broileripyörykkä" | "kanaviillokki" | "kana-vuohenjuustopasta" | "kangasrousku" | "kangastatti" | "kani" | "kantarelli" | "karjalanpiirakka" | "karpalo" | "karppisokeri" | "karvarousku" | "karviainen" | "kasslerpaisti" | "kasslerpihvi" | "kasslerpihvi/-paisti" | "kastanja" | "kastike" | "kastikejauhe" | "kasvirasvalevite" | "kasvis" | "kasvisgratiini" | "kasviskaalikääryle" | "kasviskastike" | "kasviskeitto" | "kasviskuskus" | "kasvislevite" | "kasvisliemi" | "kasvisliemikuutio" | "kasvisminestronekeitto" | "kasvispihvi" | "kasvispihvi/pyörykkä" | "kasvispiirakka" | "kasvispyörykkä" | "kasvis-sienipiirakka"

In [47]:
print(CQP_search3)

"kasvissose" | "kasvissosekeitto" | "kasviöljyvalmiste" | "katajanmarja" | "katkarapu" | "katkarapukeitto" | "katkarapumuhennos" | "katkarapu-nuudeliwokki" | "katkarapu-porkkanakeitto" | "kaurahiutale" | "kaurajuoma" | "kaurakuitunen" | "kauramakaroni" | "kaurapuuro" | "kaura-ruispuuro" | "kauravalmiste" | "kauravelli" | "kaviaari" | "kebab" | "kebableipä" | "kebabliha" | "kebakko" | "keitinpiirakka" | "keksi" | "keltuaisjauhe" | "kerma" | "kermainen" | "kermakastike" | "kermalikööri" | "kermaperuna" | "kermavaahto" | "kermavaahtospray" | "kermaviili" | "kesäkeitto" | "kesäkurpitsa" | "ketsuppi" | "kevätkääryle" | "kieli" | "kiinankaali" | "kiisseli" | "kiivi" | "kikherne" | "kikherne-perunapata" | "kikhernepyörykkä" | "kilohaili" | "kinder" | "kinkku-ananaspasta" | "kinkku-juustopiirakka" | "kinkkukastike" | "kinkkupasta" | "kinkku-pekoniruukku" | "kinkkupiirakka" | "kirjolohi" | "kirjolohifilee" | "kirsikka" | "kivennäisvesi" | "kokolihaleikkele" | "konjakki/rommi/viski" | "kookoshiutale" | "kookosjuoma" | "kookosmaito" | "kookosrasva" | "kookosvesi" | "kookosöljy" | "korianteri" | "korppu" | "korvasieni" | "korvasienikeitto" | "kreemi" | "kruskapuuro" | "krutonki" | "ksylitolipastilli" | "ksylitolipurukumi" | "kuha" | "kuivakakku" | "kukkakaali" | "kukkakaalimuhennos" | "kukkakaalisosekeitto" | "kuorrutuskastike" | "kurkku" | "kurkkukeitto" | "kurpitsa" | "kurpitsakeitto" | "kurpitsamuhennos" | "kurpitsansiemen" | "kuskus" | "kuusenkerkkä" | "kvinoa" | "kvinoarisotto" | "kylmä" | "kyssäkaali" | "kyssäkaalimuhennos" | "kääretorttu" | "kääretortun/täytekakun" | "kääretortun" | "köyhät" | "lahna" | "lakka" | "lakritsi" | "lampaan-" | "lampaankyljys" | "lampaankääpä" | "lampaanliha" | "lampaanliharulla" | "lampaanpaisti" | "lampaanpihvi" | "lanttu" | "lanttukukko" | "lanttulaatikko" | "lanttupiirakka" | "lanttusurvos" | "lasagne" | "latva-artisokka" | "lauantaimakkara" | "lehtikaali" | "lehtikaalisipsit" | "lehtisalaatti" | "lehtiselleri" | "leikkelemakkara" | "leipomoteollisuusmargariini" | "leipäpuuro" | "leipärasva" | "leivinjauhe" | "leivontamargariini" | "lenkkimakkara" | "lese" | "liha" | "lihahyytelö" | "lihakastike" | "liha-kasvispata" | "lihakeitto" | "lihakukko" | "lihakääryle" | "lihaliemi" | "lihaliemijauhe/tiiviste" | "lihamureke" | "lihapata" | "lihapiirakka" | "lihapulla" | "lihapullat" | "liha-riisipasteija" | "liha-sienimureke" | "lihasäilyke" | "liivate" | "likööri" | "lindströminpihvi" | "linssi" | "linssikeitto" | "linssipihvi/pyörykkä" | "lipeäkala"

In [48]:
print(CQP_search4)

"lohi" | "lohifilee" | "lohimurekepihvi" | "lohipasta" | "lohipiirakka" | "lohi-riisipiirakka" | "lohkoperuna" | "luumu" | "luumu-kaurapuuro" | "luumukeitto" | "luumu-kermahyytelö" | "luumukohokas" | "luumumarmeladi" | "luumu-riisijälkiruoka" | "maa-artisokka" | "maa-artisokkakeitto" | "maapähkinälevite" | "maapähkinäöljy" | "made" | "maissi" | "maissilastu" | "maissinaksu" | "maissinjyvä" | "maissintähkä" | "maissipuuro" | "maissitortilla" | "maissivelli" | "maissiöljy" | "maito" | "maitohorsma" | "maitojauhe" | "maitokastike" | "maitoperuna" | "maizena" | "majoneesi" | "makaroni" | "makaronilaatikko" | "makaronipuuro" | "makaronivelli" | "makean" | "makeinen" | "makeutusaine" | "makkara" | "makkarakastike" | "makkarakeitto" | "makkarapata" | "makkaraperunat" | "makrilli" | "maksa" | "maksakastike" | "maksalaatikko" | "maksamakkara" | "maksapaisti" | "maksapasteija" | "maksapata" | "maksapihvi" | "maltodekstriini" | "mandariini" | "mango" | "mango-chutney" | "mangoldi" | "mannapuuro" | "mannasuurimo" | "mannavelli" | "mansikka" | "mansikkahillo" | "mansikkasurvos" | "manteli" | "mantelijuoma" | "mantelikala" | "marenki" | "margariini" | "marja" | "marja-aronia" | "marjahillo" | "marjahyytelö" | "marjajuoma" | "marjamaito" | "marjapiirakka" | "marjapiirakka/marjapaistos" | "marja-raparperipiirakka" | "marjasose" | "marjatalkkuna" | "marjavaahto" | "marmeladi" | "marsipaani" | "maustekastike" | "maustekurkku" | "maustetahna" | "meetvursti" | "mehu" | "mehuhyytelö" | "mehujuomatiiviste" | "mehujää" | "meloni" | "merilevä" | "merisuola" | "metsälintu" | "mieto" | "mifu" | "mineraalisuola" | "minestronekeitto" | "misokeitto" | "moniviljapuuro" | "moussaka" | "muikku" | "muikkusäilyke" | "muksu" | "munakas" | "munakasrulla" | "munakastike" | "muna-kinkkuvuoka" | "munakoiso" | "munakoisonyytti" | "munakokkeli" | "muna-riisipasteija" | "munatoti" | "munavelli" | "munavoi" | "munkinpaistorasva" | "munkki" | "munkki/donitsi" | "munuainen" | "munuaiskastike" | "muro" | "mustaherukanlehtiuute" | "mustaherukka" | "mustajuuri" | "mustajuurimuhennos" | "mustajuurisosekeitto" | "mustapippuri" | "mustatorvisieni" | "mustekala" | "mustikka" | "mustikkahyve" | "mustikkasurvos" | "mysli" | "mämmi" | "männynherkkutatti" | "mäti" | "mätikastike" | "mätitahna" | "nahkiainen" | "nakki" | "nakkikastike" | "nakkikeitto" | "nakki-sekavihannesvuoka" | "nakkistroganoff" | "nakkisämpylä" | "nalle"

In [49]:
print(CQP_search5)

"naudan/vasikankyljys" | "naudanfilee" | "naudankylki" | "naudanlapa/etuselkä" | "naudanliha" | "naudanliha-kasvissose" | "naudanlihaleike" | "naudanliha-nuudeliwokki" | "naudanliha-pastakeitto" | "naudanliha-perunasose" | "naudanlihapihvi" | "naudanlihasuikale" | "naudanliha-tofu-nuudeliwokki" | "naudanpaisti" | "naudanpaisti-kasviswokki" | "naudanpotka" | "naudanrinta" | "naudanruho" | "nauris" | "neljän" | "neljänviljanpuuro" | "neljänviljanvelli" | "nokkonen" | "nokkoskeitto" | "nokkosmuhennos" | "nokkosohukainen" | "nuppuvihannes" | "nuudeli" | "nuudelikeitto" | "nuudeli-tofukeitto" | "nyhtökaura" | "nyhtökaura-nuudeliwokki" | "nyhtöpossu" | "näkkileipä" | "ohrahiutale" | "ohrapuuro" | "ohrasuurimo" | "ohratärkkelys" | "ohravelli" | "ohukainen" | "oliivi" | "oliiviöljy" | "olut" | "omena" | "omenahillo" | "omena-kaurahiutalepaistos" | "omenalastu" | "omenapiirakka" | "omena-rahkapiirakka" | "omena-riisipuuro" | "omenasose" | "oregano" | "osteri" | "osterikeitto" | "osterivinokas" | "paahtoleipä" | "paella" | "paistinkastike" | "paistinrasva" | "paistoöljy" | "pakastekasvissekoitus" | "palmuydinöljy" | "palmuöljy" | "palsternakka" | "palsternakkamuhennos" | "palsternakka-omenakeitto" | "panang" | "pangasius" | "pannukakku" | "papadum" | "papaija" | "pappilan" | "paprika" | "paprikajauhe" | "papu" | "papukeitto" | "papu-kesäkurpitsakeitto" | "papu-kvinoapihvi/pyörykkä" | "papumuhennos" | "papupata" | "papupihvi/pyörykkä" | "parsa" | "parsakaali" | "parsakaalimuhennos" | "parsakeitto" | "pasha" | "passionhedelmä" | "pasta" | "pastakastike" | "pasta-vihanneskeitto" | "pasteija" | "patakukko" | "pekoni" | "pellavansiemen" | "pellavansiemenrouhe" | "pellavaöljy" | "persikka" | "persikka/nektariini" | "persilja" | "peruna" | "perunahiutale" | "peruna-kasvispata" | "perunakroketti" | "peruna-kukkakaalicurry" | "perunakukko" | "perunalaatikko" | "perunalastu" | "perunamoussaka" | "perunaohukainen" | "perunapaistos" | "peruna-parsakaalisosekeitto" | "perunapihvi/pyörykkä" | "perunapiirakka" | "peruna-pinaattisose" | "peruna-porkkanasose" | "perunapuuro" | "perunaruusu" | "peruna-sipulilaatikko" | "perunasose" | "perunasosejauhe" | "perunavelli" | "perunavoitaikina" | "pestokastike" | "pihlajanmarja" | "piimä" | "piimävelli" | "piirakan" | "pikkuleipärasva" | "pilahviriisi" | "pinaatti" | "pinaattikeitto" | "pinaattikohokas" | "pinaattimuhennos" | "pinaatti-munalaatikko" | "pinaattiohukainen" | "pinaatti-riisilaatikko" | "pinjansiemen" | "piparjuuri" | "piparkakkutaikina" | "pirtelö" | "pizza" | "pizzapohja" | "popcorn" | "porilainen" | "porkkana" | "porkkanalaatikko" | "porkkanamuhennos" | "porkkanaohukainen" | "porkkana-perunasose" | "porkkanapiirakka"

In [50]:
print(CQP_search6)

"porkkana-riisipiirakka" | "porkkanasosekeitto" | "porkkanasurvos" | "poro-juustopiirakka" | "poro-kantarellipiirakka" | "porokeitto" | "poronkäristys" | "poronliha" | "poronlihamureke" | "poronmaksapihvi" | "poronpaisti" | "poro-rieskarulla" | "porsaanfilee" | "porsaankyljys" | "porsaankylki" | "porsaanleike" | "porsaanliha-kasvissose" | "porsaanliha-perunasose" | "porsaannuggetti" | "porsaanpaisti" | "porsas-kasviswokki" | "possupaisti" | "profeel" | "psyllium" | "pulla" | "pulla-" | "puna-ahven" | "punaherukka" | "punainen" | "punaista" | "punajuuri" | "punajuuri-fetamunakas" | "punajuurikeitto" | "punajuuripestokastike" | "punajuuripihvi" | "punajuuri-riisilaatikko" | "punajuuri-sinihomejuustovuoka" | "punajuuri-vuohenjuustopiirakka" | "punajuuri-vuohenjuustovuoka" | "punakaali" | "punakaalimuhennos" | "punasalaatti" | "punasipuli" | "punaviini" | "punaviinikastike" | "punikkitatti" | "puolukka" | "puolukkahillo" | "puolukkarönttönen" | "puolukkasurvos" | "purjo" | "purjo-perunasosekeitto" | "purjosipuli" | "purukumi" | "pussikeitto" | "pyttipannu" | "pähkinä" | "pähkinä-hedelmä-sekoitus" | "pähkinämureke/pyörykkä" | "pähkinäsekoitus" | "pähkinävälipala" | "päärynä" | "quorn" | "quorn-tomaattikastike" | "raakamakkara" | "raejuusto" | "raejuusto-munavoi" | "rahka" | "rahkajuoma" | "rahkamarjapiirakka" | "rahkapiirakan" | "rahkapiirakka" | "rahkavoitaikina" | "ranskanperuna" | "ranskanperunavalmiste" | "raparperi" | "raparperi-kaurahiutalepaistos" | "raparperipiirakka" | "raparperirahkapiirakka" | "raparperi-riisipuuro" | "rapu" | "rasvajauhe" | "rasvaseos" | "rasvaseoslevite" | "ratatouille" | "retiisi" | "riimiliha" | "riisi" | "riisijuoma" | "riisikakku" | "riisi-kauraseos" | "riisi-kermajälkiruokapohja" | "riisi-kvinoa-moniviljaseos" | "riisi-maissikakku" | "riisi-ohraseos" | "riisipuuro" | "riisipyörönen" | "riisi-ruisseos" | "riisisuklaa" | "riisitärkkelys" | "riisivalmiste" | "riisivelli" | "riista" | "risotto" | "rommikola" | "roomansalaatti" | "rosolli" | "rouhe" | "ruishiutale" | "ruisleipä" | "ruismallas" | "ruis-marjapuuro" | "ruis-perunapuuro" | "ruispuuro" | "ruis-riisiseos" | "ruissipsi" | "ruis-vehnä-perunataikina" | "ruisvelli" | "rukola" | "runebergintorttu" | "ruoanvalmistuskerma" | "ruoanvalmistusrasva" | "ruohosipuli" | "ruokasooda" | "ruokasuola" | "ruokaöljy" | "rusina" | "ruskea" | "ruusukaali" | "ruusukaalikeitto" | "ruusunmarja" | "ruusunmarjasose" | "rypsiporsas" | "rypsiöljy" | "rypälesokeri" | "ryynimakkara" | "rössymaito" | "rössypottu" | "röstiperuna" | "salaatinkastike" | "salaatti" | "sardiini" | "savuporo-juustokeitto" | "savuporokeitto" | "screwdriver" | "seesaminsiemen" | "seesaminuggetti" | "seiti" | "sekahedelmä" | "sekaleipä"

In [51]:
print(CQP_search7)

"sekavihannes" | "sekavihannesmuhennos" | "sellerimuhennos" | "sharon" | "siankinkku" | "siankyljys" | "siankyljys/selkä" | "siankylki" | "siankärsämö" | "sianlapa" | "sianliha" | "sianlihasuikale" | "sian" | "sianpaisti" | "sianpotka" | "sianpotka/sorkka" | "sianruho" | "siemensekoitus" | "sieni" | "sieni-juurespata" | "sieni-kaalikääryle" | "sienikastike" | "sienikastike/muhennos" | "sieni-kasvismuhennos" | "sienikeitto" | "sieni-ohrakeitto" | "sieni-ohrasuurimolaatikko" | "sieniohukainen" | "sienipihvi/pyörykkä" | "sienipiirakka" | "sieni-sipulihakkelus" | "siideri" | "siiderijuoma" | "siika" | "siirappi" | "siitakesieni" | "silakka" | "silakkafilee" | "silakkahyytelö" | "silli" | "sima" | "simpukkakastike" | "simpukkakeitto" | "sinappi" | "sinihomejuustokastike" | "sinipallas" | "sinisimpukka" | "sipuli" | "sipulikeitto" | "sipulimuhennos" | "sipulipiirakka" | "sipulirengas" | "siskonmakkarakeitto" | "sitruuna" | "sitruunakastike" | "sitruunavaahto" | "skyr" | "smetana" | "smetanalohi" | "smoothie" | "soijajuoma" | "soija-kasviskastike" | "soija-kasviskiusaus" | "soija-marja-pellava-ruis-jauheseos" | "soijanakkikastike" | "soijanakkikeitto" | "soijanakkistroganoff" | "soijapapu" | "soijapihvi" | "soijaproteiini" | "soijarouhe" | "soija-ruusunmarja-pellava-inuliinivalmiste" | "soija-ruusunmarja-pellava-valmiste" | "soijavalmiste" | "soijavälipala" | "soijaöljy" | "sokeri" | "sokeririnkeli" | "sokerivesikuorrutus" | "sorbetti" | "sorbitoli" | "spagetti" | "spagettikastikejauhe" | "spagettilihavuoka" | "suklaa" | "suklaakonvehti" | "suklaapatukka" | "suklaa-pähkinälevite" | "suklaarusina" | "sulatejuusto" | "sultsina" | "suolapähkinä-hedelmä-sekoitus" | "suolatikku" | "suppilovahvero" | "suppilovahverokeitto" | "sushi" | "sydän" | "syrnikki" | "särki" | "taateli" | "tahini" | "taimen" | "tali" | "talkkunapiimä" | "talkkunapuuro" | "tapas" | "tartarpihvi" | "tattari" | "tattaripuuro" | "tattarivelli" | "tee" | "tempeh" | "teollisuusmargariini" | "teriyaki-kanaa" | "ternimaito" | "tikka" | "tilapia" | "tilli" | "tillikastike" | "timjami" | "tippaleipä" | "tofu" | "tofu-kasviskastike" | "tofu-kasviswokki" | "tofu-nuudeliwokki" | "tofu-papukastike" | "tofu-perunavuoka" | "tofupihvi" | "tomaatti" | "tomaattikastike" | "tomaattikeitto" | "tomaatti-mozzarellapasta" | "tomaatti-mozzarellapiirakka" | "tomaattimurska" | "tomaattisalsa" | "tomaattisilakka" | "tomaattisose" | "tom" | "tonikki" | "tonnikala" | "tonnikala-makaronimuhennos" | "tonnikalapasta" | "tonnikalapihvi" | "torttupohja" | "tuontikala" | "tuorejuusto" | "tuoremehucampari" | "tuorepuuro" | "turska" | "tuulihattu"

In [52]:
print(CQP_search8)

"tyrnimarja" | "tärkkelyssiirappi" | "täysjyväriisi" | "täysksylitolipastilli" | "täysmehu" | "täytekakku" | "täytekakun/kääretortun" | "täytekakun" | "täytetty" | "unelmatortun" | "unikonsiemen" | "urheilujuoma" | "urheilujuomatiiviste" | "uunibanaani" | "uunihauki" | "uunijuurekset" | "uunikala" | "uuniomena" | "uuniperuna" | "uunisilakka" | "uunivihannekset" | "vaalea" | "vadelma" | "vadelmasurvos" | "valkokaali" | "valkopippuri" | "valkoretikka" | "valkosipuli" | "valkosipulietana" | "valkosipuliperuna" | "valkoviini" | "valkuaisjauhe" | "vanilliinisokeri" | "vanukas" | "variksenmarja" | "vasikanpaisti" | "vasikanpotka" | "vatruska" | "vehnähiutale" | "vehnänalkio" | "vehnäpuuro" | "vehnätortilla" | "vehnävelli" | "veri" | "verigreippi" | "verileipä" | "veriohukainen" | "vesi" | "vesikastanja" | "vesimeloni" | "vesirinkeli" | "wieninleike" | "vihanneskeitto" | "vihanneskrassi" | "vihannesmunavuoka" | "viikuna" | "viili" | "viina" | "viineri" | "viini" | "viinietikka" | "viiniglögi" | "viininlehti" | "viininlehtikääryle" | "viinirypäle" | "viiriäisen" | "viljaporsas" | "villirucola" | "virkistysjuoma" | "virvoitusjuoma" | "vitamiinivesi" | "vohveli" | "vohvelikuori" | "voi" | "voikreemitäyte" | "voikukka" | "voileipä" | "voileipäkakku" | "voileipäpikkelssi" | "voirinkeli" | "voisarvi" | "voitaikina" | "voitaikinarasva" | "voiöljy" | "wokatut" | "wok-kasvikset" | "vorschmack" | "vuohenputki" | "vuonankaali" | "väinönputki" | "väkevä" | "väkiviinaetikka" | "välipalajuoma" | "välipalapatukka" | "yrtti" | "yrttilevite" | "äidinmaidonkorvike" | "äidinmaito"