In [64]:
import pandas as pd

Creating dataframes

In [65]:
CQP_1 = pd.read_csv("../Datasets/CQP1.csv", sep=";")
CQP_2 = pd.read_csv("../Datasets/CQP2.csv", sep=";")
CQP_3 = pd.read_csv("../Datasets/CQP3.csv", sep=";")
CQP_4 = pd.read_csv("../Datasets/CQP4.csv", sep=";")
CQP_5 = pd.read_csv("../Datasets/CQP5.csv", sep=";")
CQP_6 = pd.read_csv("../Datasets/CQP6.csv", sep=";")
CQP_7 = pd.read_csv("../Datasets/CQP7.csv", sep=";")
CQP_8 = pd.read_csv("../Datasets/CQP8.csv", sep=";")

Inspecting the data

In [66]:
CQP_1.head()

,word,text_thread_id,Yhteensä,Suomi24 2021–2023: 2021,Suomi24 2021–2023: 2022,Suomi24 2021–2023: 2023
0,hiiva,10035487,0.002111,0.006365,0.00000,0.0
1,banaani,10041905,0.002111,0.000000,0.00689,0.0
2,hedelmä,10063435,0.002111,0.006365,0.00000,0.0
3,auringonkukkaöljy,10070341,0.002111,0.006365,0.00000,0.0
4,hoki,10085899,0.002111,0.000000,0.00689,0.0

Concatenating all dataframes into one dataframe and removing unnecessary columns

In [67]:
CQP = pd.concat([CQP_1, CQP_2, CQP_3, CQP_4, CQP_5, CQP_6, CQP_7, CQP_8])
CQP = CQP[["word", "text_thread_id"]]

Examining the new dataframe

In [68]:
CQP.head()

                word text_thread_id
0              hiiva       10035487
1            banaani       10041905
2            hedelmä       10063435
3  auringonkukkaöljy       10070341
4               hoki       10085899

In [69]:
CQP.describe()

          word  text_thread_id
count   100048          100048
unique     795           74064
top      viina        16877322
freq      4352              92