In [29]:
import pandas as pd

Creating dataframes

In [30]:
CQP_1 = pd.read_csv("../Datasets/CQP1.csv", sep=";")
CQP_2 = pd.read_csv("../Datasets/CQP2.csv", sep=";")
CQP_3 = pd.read_csv("../Datasets/CQP3.csv", sep=";")
CQP_4 = pd.read_csv("../Datasets/CQP4.csv", sep=";")
CQP_5 = pd.read_csv("../Datasets/CQP5.csv", sep=";")
CQP_6 = pd.read_csv("../Datasets/CQP6.csv", sep=";")
CQP_7 = pd.read_csv("../Datasets/CQP7.csv", sep=";")
CQP_8 = pd.read_csv("../Datasets/CQP8.csv", sep=";")

Inspecting the data

In [31]:
CQP_1.head()

,word,text_thread_id,Yhteensä,Suomi24 2021–2023: 2021,Suomi24 2021–2023: 2022,Suomi24 2021–2023: 2023
0,Σ,Σ,28.909224,28.128331,29.634402,29.010866
1,hapankaali,16796146,0.061217,0.146402,0.041341,0.000000
2,hedelmä,17969829,0.054884,0.000000,0.000000,0.151615
3,hampurilainen,18191211,0.054884,0.000000,0.000000,0.151615
4,hedelmä,17254127,0.040108,0.000000,0.130912,0.000000

Concatenating all dataframes into one dataframe and removing unnecessary columns

In [32]:
CQP = pd.concat([CQP_1, CQP_2, CQP_3, CQP_4, CQP_5, CQP_6, CQP_7, CQP_8])
CQP = CQP[["word", "text_thread_id"]]

Examining the new dataframe

In [33]:
CQP.head()

            word text_thread_id
0              Σ              Σ
1     hapankaali       16796146
2        hedelmä       17969829
3  hampurilainen       18191211
4        hedelmä       17254127

In [34]:
CQP.describe()

         word text_thread_id
count   86736          86736
unique    692          58504
top     viina       16877322
freq     4352            112

In [35]:
print(CQP)

               word text_thread_id
0                 Σ              Σ
1        hapankaali       16796146
2           hedelmä       17969829
3     hampurilainen       18191211
4           hedelmä       17254127
...             ...            ...
7926     täytekakku       17739398
7927     täytekakku       17723722
7928     täytekakku       17716602
7929     täytekakku       17710262
7930     tyrnimarja       18048742

[86736 rows x 2 columns]

Grouping food items based on the thread ID

In [36]:
food_id = CQP.groupby("text_thread_id")["word"].apply(list)
food_id = food_id[food_id.apply(lambda x: len(set(x)) >= 2)]

Inspecting the outcome

In [37]:
food_id.head()

text_thread_id
10013536             [jauhelihakeitto, pinaattikeitto]
10018155    [jauhelihakeitto, kaurapuuro, perunavelli]
10031585                             [luumu, siirappi]
10041905                       [banaani, maito, mysli]
10049647                             [mehu, punaviini]
Name: word, dtype: object

In [38]:
food_id.describe()

count             12925
unique             8296
top       [hauki, kala]
freq                148
Name: word, dtype: object

In [39]:
for food in food_id:
    print(food)

['jauhelihakeitto', 'pinaattikeitto']
['jauhelihakeitto', 'kaurapuuro', 'perunavelli']
['luumu', 'siirappi']
['banaani', 'maito', 'mysli']
['mehu', 'punaviini']
['merisuola', 'lohifilee', 'lohi']
['jauheliha', 'kebab', 'majoneesi', 'pizza']
['hoki', 'sitruuna']
['kalja', 'viini', 'viina']
['maksamakkara', 'voileipä']
['kalja', 'makkaraperunat', 'pizza', 'olut']
['banaani', 'ankerias', 'kurkku', 'kesäkurpitsa', 'kermavaahto', 'munakoiso', 'makkara', 'porkkana', 'palsternakka']
['jäätelö', 'mansikka', 'viina']
['nakki', 'puolukkahillo']
['kalja', 'kala', 'siika']
['kaali', 'makkara', 'peruna', 'sinappi', 'viini']
['peruna', 'sipuli', 'sianliha']
['tonnikala', 'sinappi']
['creme', 'banaani', 'korppu', 'mango', 'tilli']
['hauki', 'ahven', 'kuha', 'kirjolohi']
['margariini', 'pulla']
['hampurilainen', 'kebab', 'kaurapuuro']
['jauhelihakeitto', 'makkarakeitto']
['kana', 'kalkkuna', 'osterivinokas']
['kantarelli', 'kala', 'mäti', 'margariini', 'suppilovahvero']
['hedelmä', 'kahvi', 'rypsiöljy']
['hirssi', 'hedelmä', 'kakku', 'pasta', 'olut', 'rapu', 'sieni']
['juusto', 'made', 'paahtoleipä', 'rusina']
['kananmuna', 'urheilujuoma', 'viini']
['kebabliha', 'kebab']
['siika', 'viina']
['kaalikääryle', 'kaali', 'kerma', 'makkara', 'makkaraperunat', 'peruna', 'viini']
['lohi', 'olut', 'pyttipannu']
['hoki', 'kahvi']
['mehu', 'viini']
['kaali', 'jauheliha', 'kaalikeitto', 'juurekset', 'lihaliemi', 'munkki', 'naudanliha']
['kerma', 'maito']
['hauki', 'lohi']
['juusto', 'olut']
['mustapippuri', 'tomaatti', 'sushi']
['broileri', 'kala', 'lohi', 'silakka']
['ketsuppi', 'sinappi']
['chili', 'maito']
['jauheliha', 'peruna', 'porkkana', 'punajuuri']
['hauki', 'ahven', 'lohi', 'suklaa']
['timjami', 'sitruuna']
['jauhelihakeitto', 'perunalaatikko']
['lihaliemi', 'maito']
['kalja', 'viini']
['maapähkinälevite', 'olut', 'suklaa']
['kahvi', 'kana', 'kurkku']
['sianliha', 'viini']
['kalja', 'viina']
['herne', 'peruna']
['makkaraperunat', 'makkara', 'olut']
['made', 'viina']
['nakki', 'makkara']
['lanttu', 'porkkana', 'palsternakka', 'nauris', 'punajuuri']
['banaani', 'kurkku']
['kana', 'peruna', 'pulla', 'viini']
['jäätelö', 'mansikka']
['banaani', 'rahka']
['hapankaali', 'kala', 'maito']
['kahvi', 'juusto']
['kahvi', 'leivinjauhe', 'mineraalisuola', 'makaronilaatikko', 'oliiviöljy', 'rypsiöljy', 'psyllium']
['hunaja', 'kala', 'maito', 'makkara', 'pizza', 'riisi']
['juustosarvi', 'lihapiirakka']
['kurkku', 'viina']
['kerma', 'maito', 'smetana']
['avokado', 'kala', 'maito']
['juusto', 'jauhelihakeitto', 'piimä']
['jogurtti', 'punasipuli']
['kookosmaito', 'maito', 'sitruuna']
['hedelmä', 'kahvi']
['mansikka', 'suklaa']
['kahvi', 'lihaliemi', 'kerma']
['kala', 'munakoiso', 'porkkana', 'punasipuli', 'silli', 'sipuli']
['kana', 'kala']
['hiiva', 'sieni']
['jauheliha', 'peruna', 'riisi']
['hoki', 'makkara']
['kerma', 'munakastike', 'maito', 'perunalaatikko', 'siika', 'viili']
['nakki', 'peruna']
['kahvi', 'suklaa']
['chili', 'ananas', 'makaronilaatikko', 'pizza', 'punajuuri']
['kalja', 'olut']
['kurkku', 'viina']
['hedelmä', 'viini']
['kahvi', 'maito', 'ruisleipä', 'pulla', 'porsaanleike']
['viini', 'viina']
['muikku', 'makkaraperunat']
['kalja', 'kala', 'paprika']
['hampurilainen', 'kebab', 'nakki']
['purjo', 'sipuli']
['kahvi', 'viina']
['maito', 'näkkileipä']
['made', 'tikka']
['hedelmä', 'omena']
['hedelmä', 'viinirypäle']
['jauhelihakeitto', 'taateli']
['kalja', 'viini']
['kananmuna', 'pannukakku', 'tomaattikeitto']
['pinaattikeitto', 'silakka']
['donitsi', 'munkki']
['kerma', 'muro']
['kuha', 'kebabliha', 'kebab']
['jäätelö', 'viini']
['banaani', 'porkkana', 'rypsiöljy']
['hummeri', 'mannapuuro']
['jauho', 'viina']
['kala', 'lanttu', 'mustikka', 'puolukka', 'vadelma']
['jäätelö', 'tuorejuusto']
['makkaraperunat', 'makkara', 'sinappi']
['hauki', 'makkara']
['piimä', 'särki']
['hedelmä', 'appelsiini', 'omena']
['kana', 'maissi', 'lohi', 'riisi', 'psyllium']
['ahven', 'kala']
['lanttu', 'sitruuna']
['jauhelihakeitto', 'luumu']
['kala', 'silakka']
['jänis', 'poronliha']
['kaali', 'makkara', 'peruna', 'sinappi', 'viina']
['kani', 'maito']
['kala', 'kukkakaali']
['hapankaali', 'jauhelihakeitto', 'pinaattikeitto']
['nakki', 'viina']
['hernekeitto', 'bataatti', 'kalkkuna', 'lanttu', 'mäti', 'lohi', 'makkarakeitto', 'porkkana', 'perunalaatikko', 'pannukakku', 'viina']
['banaani', 'piimä', 'sipuli']
['hirvenliha', 'poronliha', 'poronkäristys']
['maitojauhe', 'maito']
['kantarelli', 'suppilovahvero']
['kala', 'jogurtti', 'naudanliha']
['kalja', 'nakki']
['kalja', 'viini']
['hampurilainen', 'pizza']
['kermalikööri', 'mehu']
['kani', 'kala']
['appelsiini', 'mehu', 'porkkana', 'omena']
['kurkku', 'ruisleipä', 'pulla']
['hedelmä', 'kaali', 'jauheliha']
['kurkku', 'suklaa']
['kirjolohi', 'lohi']
['appelsiini', 'kahvi', 'kala', 'jauheliha', 'lohi', 'munkki', 'olut', 'viina']
['piimä', 'ruisleipä']
['nakki', 'majoneesi', 'naudanpaisti']
['luumu', 'makkara']
['kana', 'jänis']
['kerma', 'maito']
['jauheliha', 'margariini']
['hedelmä', 'omena']
['hapankaali', 'juurekset', 'puolukkahillo', 'sianliha']
['nakki', 'makkara', 'tomaatti']
['peruna', 'pasta', 'riisi']
['hedelmä', 'kahvi', 'kaviaari', 'mandariini', 'omena']
['herne', 'viina']
['rusina', 'sipuli']
['jänis', 'kala']
['korianteri', 'manteli']
['maito', 'sitruuna']
['mämmi', 'makkara']
['herne', 'kahvi']
['hernekeitto', 'makaronilaatikko']
['broileri', 'risotto']
['appelsiini', 'hoki', 'kurkku', 'mandariini', 'maito', 'suklaa']
['hauki', 'kahvi']
['kalja', 'viina']
['persikka', 'olut']
['kookosöljy', 'mehu', 'oliiviöljy', 'puolukka', 'sieni', 'väkiviinaetikka']
['kala', 'kahvi', 'luumu', 'porkkana', 'ruisleipä']
['hernekeitto', 'papu']
['kana', 'katkarapu', 'tonnikala']
['lakka', 'mustikka', 'mansikka', 'olut', 'puolukka']
['appelsiini', 'omena']
['pizza', 'risotto']
['jäätelö', 'urheilujuomatiiviste']
['avokado', 'ananas', 'mehu']
['kurkku', 'porkkana']
['herne', 'kala', 'jauheliha', 'maissi']
['kurkku', 'makkara']
['jäätelö', 'makkaraperunat', 'rahka']
['munkki', 'olut']
['kana', 'kala']
['kermaviili', 'kaurahiutale']
['mustikka', 'mehu']
['kaviaari', 'lohi']
['olut', 'viina']
['ananas', 'pizza']
['jauhelihakeitto', 'nauris']
['kurkku', 'viina']
['mehu', 'puolukka']
['hedelmä', 'omena']
['kalja', 'likööri', 'makkara']
['kahvi', 'olut']
['hauki', 'kampela', 'kala', 'lahna']
['appelsiini', 'kaali', 'mustikka', 'mustaherukka', 'manteli', 'porkkana', 'parsa', 'omena', 'ohrapuuro', 'purjo', 'psyllium', 'sipuli', 'vadelma']
['omena', 'päärynä']
['mehu', 'mansikka']
['kahvi', 'lakritsi']
['chili', 'kebab']
['riista', 'viina']
['kurkku', 'kesäkurpitsa']
['maito', 'pulla']
['lanttu', 'porkkana', 'nauris', 'punajuuri']
['kebab', 'pizza']
['likööri', 'viini']
['hapankaali', 'tofu']
['suklaa', 'viina']
['kahvi', 'maito']
['hedelmä', 'munkki', 'viini']
['kala', 'kirjolohi', 'punajuuri']
['kana', 'kerma', 'margariini', 'papupata', 'nuudeli', 'pulla', 'rypsiöljy', 'riisi', 'viini']
['korppu', 'viina']
['hedelmä', 'jäätelö', 'jogurtti', 'rahka', 'välipalapatukka']
['kahvi', 'peruna']
['lahna', 'omena']
['maissi', 'porkkana', 'popcorn']
['sitruuna', 'valkosipuli']
['hirvenliha', 'lampaanliha']
['olut', 'valkosipuli']
['jauho', 'margariini']
['kaakaojauhe', 'kiisseli', 'kerma']
['jauhelihakeitto', 'kaviaari', 'porkkanalaatikko']
['kahvi', 'makkara', 'viina']
['hedelmä', 'papaija', 'sitruuna']
['kana', 'kala']
['olut', 'viina']
['made', 'olut', 'riisi']
['hoki', 'viina']
['kala', 'lohi', 'rypsiporsas']
['kaurapuuro', 'maito', 'sipuli']
['pulla', 'suklaa']
['oliiviöljy', 'rypsiöljy']
['jänis', 'punaviini']
['kahvi', 'kerma', 'kermavaahto', 'maito']
['jauhelihakeitto', 'makkarakeitto']
['jauhelihakeitto', 'munkki']
['jauhelihakeitto', 'perunalaatikko']
['banaani', 'manteli']
['juusto', 'maito', 'piimä']
['muro', 'piimä']
['olut', 'viina']
['kana', 'olut']
['persikka', 'pulla']
['hedelmä', 'creme', 'kahvi', 'ketsuppi', 'nakki']
['pinaattikeitto', 'piimä']
['kiisseli', 'makkara']
['olut', 'viini']
['hoki', 'kahvi']
['jauhelihakeitto', 'lanttu']
['kebab', 'pizza']
['appelsiini', 'juusto', 'kurkku']
['kala', 'viina']
['jauho', 'sieni']
['kana', 'kahvi', 'maito', 'porkkana', 'riisi', 'sipuli']
['ankerias', 'kala', 'juusto']
['paprika', 'valkokaali']
['kahvi', 'kaalikeitto', 'suklaa']
['banaani', 'lenkkimakkara', 'makkara']
['munkki', 'makkara']
['kebab', 'ketsuppi', 'makkaraperunat', 'majoneesi', 'sipuli', 'sinappi', 'valkosipuli']
['herne', 'jänis', 'kala', 'äidinmaito']
['kananmuna', 'makaronilaatikko']
['juusto', 'kebab', 'pizza']
['kala', 'nakki']
['kala', 'porkkana']
['kalja', 'kuha', 'katkarapu', 'mustikka']
['hauki', 'ahven', 'siika']
['kahvi', 'omena']
['kaurahiutale', 'maito']
['juusto', 'lasagne', 'margariini', 'pulla']
['munkki', 'papu']
['kahvi', 'viina']
['karpalo', 'puolukka']
['kebab', 'pizza']
['jauhelihakeitto', 'perunalaatikko']
['lahna', 'rapu']
['hampurilainen', 'kaurapuuro', 'pizza']
['sitruuna', 'siika']
['kahvi', 'kurkku', 'lahna', 'munkki', 'viina']
['hernekeitto', 'fruktoosi', 'juusto', 'kani', 'kalkkuna', 'kurkku', 'margariini', 'pekoni', 'olut', 'näkkileipä', 'ruisleipä']
['jauhelihakeitto', 'pinaattikeitto']
['hauki', 'kala', 'lahna']
['maito', 'olut']
['nakki', 'makkara']
['kahvi', 'maito']
['kala', 'lanttukukko', 'muikku', 'piimä', 'siirappi']
['kurkku', 'tomaatti']
['kalja', 'olut']
['jauhelihakeitto', 'kaalilaatikko']
['kahvi', 'olut']
['kala', 'juurekset']
['jauhelihakeitto', 'porkkanalaatikko']
['korvasieni', 'sieni']
['kana', 'katkarapu', 'lohi', 'maissi', 'riista', 'tonnikala']
['nakkikeitto', 'sipuli']
['kahvi', 'katkarapu', 'silakka']
['makkarakeitto', 'perunalaatikko', 'siskonmakkarakeitto']
['chili', 'pannukakku']
['lauantaimakkara', 'majoneesi']
['hillo', 'sinappi']
['kana', 'kurkku']
['aprikoosi', 'piimä', 'sieni']
['kerma', 'lohi']
['rapu', 'riisi']
['kebab', 'pizza']
['kalja', 'olut']
['maito', 'särki']
['kalakeitto', 'ruisleipä', 'poronkäristys']
['jauhelihakeitto', 'pinaattikeitto']
['nakkikastike', 'peruna']
['kirsikka', 'makkaraperunat']
['kaali', 'makkara', 'nakki', 'viini']
['kala', 'lohi']
['kalapaistos', 'jauhelihakeitto']
['nakki', 'viini']
['mustaherukka', 'punaherukka']
['kalja', 'lohi']
['kahvi', 'viini']
['kurkku', 'suklaa']
['juuriselleri', 'juurekset', 'palsternakka']
['mehu', 'peruna']
['kalapuikko', 'kalja', 'rapu', 'suklaa', 'urheilujuoma']
['jäätelö', 'mustaherukka']
['kahvi', 'juusto', 'mustaherukka', 'mehu', 'margariini']
['grillimakkara', 'lihapiirakka']
['kana', 'jauho']
['hillo', 'mehu', 'maito']
['jauhelihakeitto', 'porkkanalaatikko']
['leivinjauhe', 'tuorepuuro']
['hillo', 'kermavaahto', 'pulla']
['jauhelihakeitto', 'piimä']
['hiiva', 'jauheliha', 'olut']
['kala', 'lohi']
['lihapiirakka', 'makkaraperunat']
['kasvissose', 'muikku', 'maksalaatikko', 'pellavaöljy']
['hedelmä', 'kahvi']
['kahvi', 'kerma', 'munkki']
['jauhelihakeitto', 'näkkileipä']
['kala', 'tofu']
['kana', 'lohi']
['hauki', 'kala', 'jogurtti', 'kerma', 'maito', 'piimä', 'rahka']
['viini', 'viina']
['kala', 'kahvi', 'juusto', 'makkara']
['kala', 'lauantaimakkara', 'makkara', 'tomaatti']
['kahvi', 'jänis']
['hiiva', 'olut', 'piimä']
['grillimakkara', 'maito', 'olut']
['hedelmä', 'pulla']
['kananmuna', 'jauhelihakeitto']
['grillimakkara', 'chili']
['jauhelihakeitto', 'lohi']
['kookosöljy', 'oliiviöljy']
['maito', 'psyllium', 'tomaatti']
['kala', 'lahna']
['pannukakku', 'omena']
['kalja', 'kurkku']
['kana', 'kala']
['banaani', 'peruna']
['lakritsi', 'maksalaatikko', 'makkara', 'mansikka', 'peruna', 'riisi']
['olut', 'viini']
['hauki', 'kala']
['auringonkukkaöljy', 'tomaatti', 'sitruuna', 'valkoviini']
['aprikoosi', 'kirsikka', 'kiivi', 'luumu', 'persikka', 'omena', 'päärynä', 'suklaa']
['kaalilaatikko', 'lohi']
['karjalanpiirakka', 'kalakukko']
['kahvi', 'makkara', 'makkaraperunat', 'pulla']
['maito', 'porkkana']
['hernekeitto', 'ruisleipä']
['hunaja', 'pizza', 'peruna', 'riisi', 'sitruuna', 'viina']
['hummeri', 'kala', 'kuha', 'kirjolohi', 'made', 'siika']
['kananmuna', 'kana', 'sieni', 'viina']
['made', 'särki']
['makkara', 'pekoni']
['hunaja', 'olut']
['makaronilaatikko', 'pulla']
['hoki', 'kana', 'parsa']
['hedelmä', 'kahvi']
['kahvi', 'pulla']
['kananmuna', 'nakki']
['kala', 'kirjolohi', 'lohi', 'makkara', 'olut']
['jauho', 'nakki']
['hoki', 'pulla']
['mustikka', 'mansikka']
['kurkku', 'lakka']
['hapankaali', 'härkis', 'kurkku', 'kookosöljy', 'misokeitto', 'maito', 'lohi', 'parsakaali', 'tomaatti', 'suklaa']
['kahvi', 'viini']
['maito', 'viina']
['banaani', 'viina']
['riisipuuro', 'riisi']
['jauhelihakastike', 'pasta']
['herne', 'papu']
['appelsiini', 'kuha']
['banaani', 'kurkku']
['broileri', 'kana', 'kala', 'juurekset', 'jauheliha', 'pekoni', 'ruisleipä', 'sinappi', 'viina']
['hampurilainen', 'parsa']
['kahvi', 'lihapiirakka', 'maito', 'mehu', 'pulla']
['grillimakkara', 'juusto', 'jauheliha', 'paprika', 'omena', 'tomaatti']
['kana', 'kuha']
['perunapuuro', 'tattari']
['munuainen', 'sipuli']
['kahvi', 'nakki', 'nakkikastike', 'peruna', 'pyttipannu']
['appelsiini', 'viina']
['jauhelihakeitto', 'munkki']
['kahvi', 'maito', 'paahtoleipä', 'omena']
['mämmi', 'siirappi']
['banaani', 'nakki']
['hernekeitto', 'sianliha', 'valkosipuli']
['juusto', 'nakki', 'mätitahna']
['kala', 'nauris']
['ketsuppi', 'makkaraperunat', 'sinappi', 'sipuli']
['hampurilainen', 'jauhelihapihvi']
['kahvi', 'munuainen', 'peruna', 'tomaatti']
['kala', 'nuudelikeitto', 'uunikala']
['ananas', 'pizza', 'olut']
['makkara', 'viina']
['munakas', 'pekoni']
['kalja', 'olut']
['hauki', 'kala']
['kalja', 'viini']
['chili', 'paprika']
['mustikka', 'mansikka']
['hoki', 'makkaraperunat']
['kahvi', 'pulla']
['herkkutatti', 'nakki']
['nakki', 'pizza']
['hedelmä', 'viini']
['banaani', 'mustikka']
['herajauhe', 'pulla']
['oliiviöljy', 'rypsiöljy']
['ahven', 'kala']
['hernekeitto', 'makkara', 'sinappi']
['kalakeitto', 'kakku', 'kahvi', 'jauheliha', 'lihakeitto', 'olut', 'silli']
['mustikka', 'puolukka']
['maksamakkara', 'ruisleipä']
['kana', 'kahvi', 'kurpitsa', 'naudanliha', 'rapu', 'sipuli']
['kala', 'sieni']
['appelsiini', 'mandariini', 'päärynä', 'sitruuna']
['kebab', 'muikku']
['jauhelihakeitto', 'jauhelihakastike']
['pulla', 'viini']
['karjalanpiirakka', 'makaronilaatikko']
['kana', 'kebab', 'sieni']
['sipuli', 'valkosipuli']
['kala', 'kuha']
['kalja', 'kahvi', 'maito', 'olut', 'viina']
['kahvi', 'meloni', 'mehujää', 'mango']
['kala', 'särki', 'viini']
['kana', 'kala', 'maito', 'pizza']
['lakritsi', 'kebab', 'mustikka', 'täytekakku']
['maito', 'perunalaatikko']
['jogurtti', 'maito', 'piimä', 'viina', 'viili']
['kaali', 'jauhelihakeitto', 'ruisleipä']
['lihapiirakka', 'olut']
['kampela', 'jauhelihakeitto']
['kala', 'kirjolohi', 'lohi', 'tilli']
['kana', 'kalja', 'mehu']
['kahvi', 'särki']
['mehu', 'pasta']
['kuha', 'peruna']
['karpalo', 'mehu']
['munakokkeli', 'pekoni', 'tomaatti']
['nakki', 'viina']
['makkaraperunat', 'makkara']
['kala', 'kalaliemi']
['hunaja', 'kani', 'persikka']
['hauki', 'kala']
['hedelmä', 'mansikka', 'tomaatti']
['hedelmä', 'kahvi', 'sianliha', 'viini']
['kanaviillokki', 'kaurapuuro', 'margariini', 'peruna', 'ruisleipä', 'tonnikala']
['hampurilainen', 'kalakeitto', 'kaurapuuro']
['hernekeitto', 'silakka']
['kananmuna', 'puolukka']
['hedelmä', 'viina']
['kala', 'vohveli']
['kala', 'turska']
['kaurapuuro', 'kermavaahto', 'maito']
['kalja', 'pulla', 'viina']
['pizza', 'viina']
['kalja', 'kala', 'viina']
['katkarapu', 'muikku']
['avokado', 'vesimeloni']
['kermavaahto', 'mämmi', 'perunasose']
['ketsuppi', 'tomaatti']
['makkara', 'olut']
['olut', 'raparperi', 'viina']
['jauhelihakeitto', 'silli']
['banaani', 'kaurapuuro', 'pekoni', 'voileipä']
['kala', 'kaali']
['kalja', 'olut', 'viini']
['ananas', 'pizza', 'sipuli']
['olut', 'viini']
['jauheliha', 'lehtikaalisipsit', 'pizza', 'olut', 'viini', 'viina']
['kana', 'muikku']
['kurkku', 'kerma']
['olut', 'pulla', 'viina']
['hedelmä', 'lakka', 'mansikka', 'mustikka', 'munakoiso', 'puolukka', 'tomaatti', 'variksenmarja']
['hauki', 'kala']
['makkara', 'sinappi']
['kahvi', 'kivennäisvesi', 'mustikka', 'maito', 'luumu', 'omena', 'olut', 'punaviini', 'valkoviini']
['makkara', 'olut']
['kana', 'viina']
['hauki', 'kuha', 'made']
['kuha', 'maksalaatikko']
['kahvi', 'viini']
['jauhelihakeitto', 'viina']
['jauhelihakeitto', 'perunalaatikko']
['juusto', 'maksalaatikko', 'paprika']
['hiiva', 'maito']
['kaalikääryle', 'makkaraperunat', 'makkara', 'peruna', 'olut', 'sinappi']
['meetvursti', 'ohukainen']
['hampurilainen', 'kakku']
['pizza', 'olut']
['made', 'porkkana']
['inkivääri', 'oliivi']
['hauki', 'kala']
['herne', 'kebab']
['kaali', 'kaviaari']
['kaurapuuro', 'ruisleipä']
['maito', 'piimä']
['kalja', 'maito']
['kuha', 'sushi']
['kalkkuna', 'kurkku', 'sipuli']
['appelsiini', 'sipuli']
['jauhelihakeitto', 'ruisleipä']
['mäti', 'rahka', 'raejuusto']
['kala', 'lakka']
['kalkkuna', 'kana', 'viina']
['kala', 'muikku', 'lohi', 'silakka']
['kala', 'lampaanliha', 'kirjolohi']
['kurkku', 'maito']
['munkki', 'maito']
['hedelmä', 'särki']
['jauheliha', 'makkara']
['chili', 'sianliha']
['hedelmä', 'nakki', 'porkkana']
['mustikka', 'mansikka']
['kana', 'riisi']
['kahvi', 'made', 'suklaa']
['chili', 'kermalikööri', 'mehu']
['kala', 'silli']
['kalakukko', 'rössypottu']
['makrilli', 'viina']
['appelsiini', 'sitruuna']
['herne', 'margariini', 'makkara', 'makaroni']
['kana', 'nuudeli']
['kahvi', 'pulla']
['kermavaahto', 'silli']
['maito', 'olut']
['appelsiini', 'lanttu', 'kesäkurpitsa', 'makaroni', 'porkkana', 'peruna', 'omena', 'nokkonen', 'tomaattimurska', 'tomaatti', 'sipuli', 'valkosipuli']
['hunaja', 'viineri']
['rusina', 'särki']
['avokado', 'appelsiini']
['kahvi', 'kana']
['porkkana', 'punajuuri']
['banaani', 'maito']
['juusto', 'pizza']
['jänis', 'lohi']
['banaani', 'kahvi']
['maito', 'piimä']
['hauki', 'kala', 'särki']
['kalja', 'margariini', 'porkkana', 'peruna', 'omena']
['hampurilainen', 'kahvi']
['kurkku', 'viina']
['kana', 'kala', 'jauheliha', 'oliiviöljy', 'tofu']
['peruna', 'viinirypäle']
['jauheliha', 'pizza']
['kalja', 'viina']
['kana', 'juurekset', 'jauheliha']
['mustikka', 'mansikka', 'sipuli']
['sitruuna', 'uuniperuna']
['hauki', 'kana']
['mämmi', 'siirappi']
['ananas', 'hoki', 'viina']
['mustikka', 'mansikka']
['perunavelli', 'olut', 'täytekakku']
['ankerias', 'jauhelihakeitto']
['hedelmä', 'banaani', 'kahvi', 'munkki', 'maito', 'suklaa']
['rapu', 'viina']
['jauho', 'tapas']
['kahvi', 'pulla']
['olut', 'punaviini']
['nakki', 'pulla']
['hernekeitto', 'kananmuna']
['made', 'näkkileipä']
['lakka', 'mustikka']
['kalja', 'viini']
['nauris', 'punajuuri']
['hampurilainen', 'banaani', 'kahvi', 'omena']
['jauhelihakeitto', 'makkaraperunat']
['kana', 'lahna']
['broileri', 'peruna']
['ananas', 'kaali']
['banaani', 'mandariini', 'taateli']
['hoki', 'olut']
['peruna', 'pannukakku']
['sipuli', 'silli']
['hampurilainen', 'makkaraperunat', 'pekoni']
['kana', 'pulla']
['hedelmä', 'tapas', 'spagetti']
['jauhelihakeitto', 'maksalaatikko']
['lakka', 'nakki']
['kurkku', 'tomaatti']
['kala', 'juurekset', 'mansikka']
['banaani', 'mansikka', 'olut', 'pulla', 'ruisleipä', 'suklaa', 'viini']
['hedelmä', 'peruna']
['kahvi', 'olut', 'poronpaisti', 'viina']
['kala', 'silli']
['kurkku', 'pizza', 'sieni']
['hampurilainen', 'ketsuppi']
['hampurilainen', 'grillimakkara']
['mämmi', 'maksalaatikko']
['kananmuna', 'olut', 'soijarouhe']
['kakku', 'sianliha']
['paprika', 'valkokaali']
['hummus', 'nakki', 'lohi']
['hoki', 'kahvi', 'maito', 'sipuli', 'viina']
['hedelmä', 'munkki', 'puolukka']
['kala', 'taimen']
['pulla', 'täytekakku']
['purjosipuli', 'sipuli']
['kahvi', 'suklaa']
['fruktoosi', 'viina']
['hampurilainen', 'makkara']
['nakki', 'makkara', 'tomaatti', 'viini']
['kalja', 'linssi']
['kananmuna', 'paprika', 'tonnikala']
['hernekeitto', 'hampurilainen', 'pizza', 'pasta']
['kana', 'pannukakku']
['muikku', 'made']
['viini', 'viina']
['pasta', 'riisi']
['kahvi', 'olut']
['nakki', 'olut']
['munkki', 'makkara', 'peruna']
['majoneesi', 'paahtoleipä', 'sitruuna']
['perunalaatikko', 'perunasose', 'peruna']
['kala', 'rapu', 'silakka']
['mansikka', 'oliivi']
['juurekset', 'margariini', 'sinappi']
['jäätelö', 'munkki']