In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx

In [8]:
fineli_data = pd.read_csv("../Datasets/fineli.csv", sep=";")
fineli_data = fineli_data[["name", "energia, laskennallinen (kJ)", "rasva (g)", "hiilihydraatti imeytyvä (g)", "proteiini (g)", "alkoholi (g)"]]

fineli_data.head()

,name,"energia, laskennallinen (kJ)",rasva (g),hiilihydraatti imeytyvä (g),proteiini (g),alkoholi (g)
0,Ahven,345,0.7,0,18.8,0
1,"Ahven, leivitetty, paistettu",660,6.5,4.7,19.9,0
2,"Ahven, paistettu, ei korppujauhoja",600,6.8,<0.1,20.5,0
3,"Ahven, paistettu voissa, ei korppujauhoja",595,7.3,<0.1,19.1,0
4,"Ahvenet foliossa, voissa",496,4.1,0.6,19.5,0

In [6]:
CQP_1 = pd.read_csv("../Datasets/CQP1.csv", sep=";")
CQP_2 = pd.read_csv("../Datasets/CQP2.csv", sep=";")
CQP_3 = pd.read_csv("../Datasets/CQP3.csv", sep=";")
CQP_4 = pd.read_csv("../Datasets/CQP4.csv", sep=";")
CQP_5 = pd.read_csv("../Datasets/CQP5.csv", sep=";")
CQP_6 = pd.read_csv("../Datasets/CQP6.csv", sep=";")
CQP_7 = pd.read_csv("../Datasets/CQP7.csv", sep=";")
CQP_8 = pd.read_csv("../Datasets/CQP8.csv", sep=";")

CQP = pd.concat([CQP_1, CQP_2, CQP_3, CQP_4, CQP_5, CQP_6, CQP_7, CQP_8])
CQP = CQP[["word", "text_thread_id"]]

CQP.head()

            word text_thread_id
0              Σ              Σ
1     hapankaali       16796146
2        hedelmä       17969829
3  hampurilainen       18191211
4        hedelmä       17254127

Removing duplicates from CQP data. This list will be used as a filter for the Fineli dataframe

In [23]:
food_filter = CQP["word"].dropna().str.lower().drop_duplicates().tolist()
food_filter.remove('σ')

print(food_filter)
print(len(food_filter))

['hapankaali', 'hedelmä', 'hampurilainen', 'ananas', 'banaani', 'ahven', 'hauki', 'hernekeitto', 'bataatti', 'chili', 'broileri', 'hillo', 'herne', 'appelsiini', 'hiiva', 'anjovis', 'avokado', 'ateriankorvike', 'etana', 'hunaja', 'hummeri', 'ahvenet', 'hoki', 'borssikeitto', 'hirssi', 'herkkusieni', 'haaparousku', 'grillimakkara', 'creme', 'basilika', 'auringonkukansiemen', 'aromisuola', 'hirvenliha', 'donitsi', 'blini', 'ankerias', 'herkkutatti', 'granaattiomena', 'graavilohi', 'fruktoosi', 'etikkakurkku', 'energiajuoma', 'elovena', 'chiansiemen', 'broilerikeitto', 'broilerifilee', 'aprikoosi', 'hummus', 'herkkusienikeitto', 'booli', 'amarantti', 'hedelmäsalaatti', 'greippi', 'hirvenpaisti', 'hillosipulisäilyke', 'herneenverso', 'heraproteiinikonsentraatti', 'herajauhe', 'hedelmäjuoma', 'hedelmähillo', 'hasselpähkinäjuoma', 'hapanlohko', 'hapankurkku', 'hapankorppu', 'hapankaalikeitto', 'hampunsiemen', 'guava', 'fenkolikeitto', 'fenkoli', 'etikkasienisäilyke', 'etikkapunajuuri', 'erikoishedelmä', 'chorizo', 'broilerisuikale', 'broilerinleike', 'broilerikastike', 'broilerifileesuikale', 'bambunverso', 'avokadoöljy', 'avokadopasta', 'auringonkukkaöljy', 'ateriasalaatti', 'aprikoosisose', 'ananassalsa', 'hirssipuuro', 'hernemuhennos', 'grillivartaat', 'glögijuoma', 'appelsiiniriisi', 'hollandaisekastike', 'broileripata', 'bearnaisekastike', 'appelsiinimarmeladi', 'kahvi', 'kala', 'jäätelö', 'kani', 'jänis', 'kana', 'jauheliha', 'kakku', 'kaali', 'kalkkuna', 'juurekset', 'kananmuna', 'kaalilaatikko', 'juusto', 'kalakeitto', 'kaalikääryle', 'karjalanpiirakka', 'kanaviillokki', 'kalja', 'kalakastike', 'kaakaojauhe', 'jauhelihakeitto', 'kalapuikko', 'jauho', 'kasvispihvi', 'kanakeitto', 'jauhelihakastike', 'kalakukko', 'kasvisliemikuutio', 'kaalikeitto', 'jogurtti', 'härkis', 'karviainen', 'karpalo', 'kantarelli', 'inkivääri', 'jauhelihapihvi', 'kampela', 'kaalipata', 'jäävuorisalaatti', 'kasviskeitto', 'kasslerpihvi', 'karvarousku', 'karppisokeri', 'kangasrousku', 'kalkkunaleike', 'juuriselleri', 'kanapata', 'kalapaistos', 'kahvijuoma', 'juustokeitto', 'kasvispyörykkä', 'kasvisliemi', 'kasviskastike', 'kasvisgratiini', 'kasvirasvalevite', 'kanaliemikuutio', 'kanaliemi', 'kanakastike', 'kalaliemikuutio', 'kalaliemi', 'jääsalaatti', 'juustonaksu', 'juolukka', 'joulutorttu', 'italianpata', 'kastanja', 'kangastatti', 'kalalevite', 'kaakaojuoma', 'juustotikku', 'juustosilakat', 'juustopiirakka', 'juuressosekeitto', 'kasslerpaisti', 'kalapiirakka', 'kalamureke', 'kaalipiirakka', 'juustosarvi', 'hunajameloni', 'kebab', 'kurkku', 'kuha', 'ketsuppi', 'kebabliha', 'lauantaimakkara', 'linssi', 'kivennäisvesi', 'lanttulaatikko', 'lanttu', 'lahna', 'kirjolohi', 'korppu', 'lasagne', 'lakka', 'kokolihaleikkele', 'kaurapuuro', 'kukkakaali', 'kookosöljy', 'katkarapu', 'lihapiirakka', 'kerma', 'lihamureke', 'lihahyytelö', 'kääretorttu', 'lipeäkala', 'lakritsi', 'kurpitsa', 'korvasieni', 'kirsikka', 'kiivi', 'kesäkeitto', 'kaviaari', 'linssikeitto', 'lihapulla', 'lehtikaali', 'korianteri', 'kesäkurpitsa', 'kaurajuoma', 'likööri', 'liivate', 'lenkkimakkara', 'kiisseli', 'leivinjauhe', 'leikkelemakkara', 'lanttukukko', 'kurpitsakeitto', 'krutonki', 'kookosrasva', 'kookosmaito', 'kiinankaali', 'kermavaahto', 'lihakastike', 'lese', 'lehtisalaatti', 'latva-artisokka', 'kuusenkerkkä', 'kuskus', 'kuivakakku', 'kaurahiutale', 'kasvissosekeitto', 'lihapata', 'lihaliemi', 'lihakeitto', 'kermaviili', 'lihasäilyke', 'lihakukko', 'leivontamargariini', 'leipärasva', 'lehtiselleri', 'lehtikaalisipsit', 'lanttupiirakka', 'lampaanliha', 'lampaankääpä', 'kyssäkaali', 'kvinoa', 'kurpitsansiemen', 'ksylitolipurukumi', 'kirjolohifilee', 'kinkkupiirakka', 'kilohaili', 'kikherne', 'kermaperuna', 'kermakastike', 'kauravelli', 'katkarapukeitto', 'katajanmarja', 'lampaanpaisti', 'kukkakaalimuhennos', 'ksylitolipastilli', 'korvasienikeitto', 'kookosvesi', 'kookosjuoma', 'kevätkääryle', 'kermalikööri', 'kauravalmiste', 'kauramakaroni', 'katkarapumuhennos', 'kasvissose', 'lindströminpihvi', 'kinkkupasta', 'kinkkukastike', 'maissi', 'makkaraperunat', 'makkara', 'lohi', 'maito', 'made', 'nakki', 'mämmi', 'munavoi', 'munkki', 'mansikka', 'muikku', 'margariini', 'muro', 'maksalaatikko', 'maksakastike', 'makaroni', 'majoneesi', 'mehu', 'mustekala', 'mustikka', 'meloni', 'munakas', 'makaronilaatikko', 'mäti', 'merilevä', 'meetvursti', 'marjapiirakka', 'maksamakkara', 'maitojauhe', 'munakoiso', 'marmeladi', 'mandariini', 'nakkikeitto', 'merisuola', 'mannapuuro', 'mustaherukka', 'munuainen', 'mehujää', 'manteli', 'mansikkahillo', 'mango', 'maksapasteija', 'nahkiainen', 'nakkikastike', 'mustapippuri', 'mifu', 'marenki', 'makrilli', 'makkarakeitto', 'maissintähkä', 'luumu', 'mätitahna', 'mysli', 'metsälintu', 'mantelijuoma', 'maltodekstriini', 'maksapata', 'makkarakastike', 'lohifilee', 'marsipaani', 'nakkisämpylä', 'mustatorvisieni', 'munavelli', 'munatoti', 'munakokkeli', 'munakastike', 'munakasrulla', 'moussaka', 'misokeitto', 'minestronekeitto', 'mineraalisuola', 'maustekurkku', 'marjahillo', 'marja-aronia', 'mannavelli', 'mangoldi', 'makkarapata', 'makaronivelli', 'maizena', 'maissiöljy', 'maissinjyvä', 'maapähkinäöljy', 'maa-artisokka', 'luumumarmeladi', 'luumukeitto', 'lohkoperuna', 'lohipiirakka', 'lohipasta', 'mätikastike', 'männynherkkutatti', 'mustikkasurvos', 'mustajuuri', 'munuaiskastike', 'muikkusäilyke', 'mehujuomatiiviste', 'marjasose', 'mansikkasurvos', 'maksapihvi', 'maksapaisti', 'maissipuuro', 'maapähkinälevite', 'moniviljapuuro', 'maitokastike', 'olut', 'omena', 'peruna', 'pasta', 'perunalaatikko', 'pizza', 'porkkana', 'piimä', 'pakastekasvissekoitus', 'nyhtökaura', 'pinaattikeitto', 'nauris', 'oliiviöljy', 'paprika', 'pannukakku', 'omenapiirakka', 'nuudeli', 'parsa', 'naudanliha', 'pekoni', 'palmuöljy', 'oliivi', 'porkkanalaatikko', 'paahtoleipä', 'naudanpaisti', 'näkkileipä', 'naudanlihapihvi', 'perunasose', 'persikka', 'pinaatti', 'parsakaali', 'papupata', 'palsternakka', 'omenasose', 'ohukainen', 'naudanfilee', 'perunahiutale', 'nokkonen', 'pizzapohja', 'pihlajanmarja', 'perunavelli', 'perunapiirakka', 'persilja', 'papu', 'pangasius', 'oregano', 'piparjuuri', 'pellavaöljy', 'pasha', 'osteri', 'omenahillo', 'ohrapuuro', 'pinaattiohukainen', 'perunalastu', 'papukeitto', 'paella', 'popcorn', 'pirtelö', 'piparkakkutaikina', 'piimävelli', 'pestokastike', 'perunapuuro', 'perunakukko', 'pellavansiemenrouhe', 'pellavansiemen', 'patakukko', 'pasteija', 'pastakastike', 'passionhedelmä', 'paprikajauhe', 'papaija', 'palmuydinöljy', 'osterivinokas', 'ohravelli', 'ohrasuurimo', 'nyhtöpossu', 'nuudelikeitto', 'porkkanamuhennos', 'pinaattikohokas', 'papumuhennos', 'ohratärkkelys', 'nokkoskeitto', 'neljänviljanpuuro', 'naudanrinta', 'naudanlihasuikale', 'pinjansiemen', 'riisi', 'päärynä', 'rapu', 'pulla', 'raejuusto', 'puolukka', 'punaviini', 'rusina', 'riisipuuro', 'porsaanfilee', 'rosolli', 'seiti', 'rypsiöljy', 'ruisleipä', 'punajuuri', 'puna-ahven', 'riista', 'poronliha', 'puolukkahillo', 'rahka', 'ruusukaali', 'risotto', 'raparperi', 'rahkapiirakka', 'pähkinäsekoitus', 'puolukkasurvos', 'sardiini', 'runebergintorttu', 'pyttipannu', 'ranskanperuna', 'rypsiporsas', 'ruusunmarjasose', 'ruokasuola', 'ruispuuro', 'riisikakku', 'purjosipuli', 'purjo', 'psyllium', 'porsaanpaisti', 'porsaankyljys', 'poronkäristys', 'porokeitto', 'porkkanasosekeitto', 'ruohosipuli', 'punikkitatti', 'punasipuli', 'punaherukka', 'riisivelli', 'savuporokeitto', 'rössypottu', 'ryynimakkara', 'ruusunmarja', 'ruusukaalikeitto', 'ruoanvalmistuskerma', 'rukola', 'ruisvelli', 'ruismallas', 'ruishiutale', 'roomansalaatti', 'riisijuoma', 'retiisi', 'ratatouille', 'raparperipiirakka', 'rahkavoitaikina', 'rahkajuoma', 'raakamakkara', 'quorn', 'pussikeitto', 'punaviinikastike', 'punasalaatti', 'punakaali', 'possupaisti', 'porsaanleike', 'poronpaisti', 'poronmaksapihvi', 'porkkanasurvos', 'ruissipsi', 'punajuurikeitto', 'seesaminsiemen', 'riisisuklaa', 'riimiliha', 'sieni', 'sinappi', 'silakka', 'suklaa', 'sima', 'tonnikala', 'sitruuna', 'tomaatti', 'sushi', 'sianliha', 'silli', 'särki', 'siika', 'tikka', 'sipuli', 'spagetti', 'tilapia', 'sulatejuusto', 'turska', 'tuorejuusto', 'tofu', 'suppilovahvero', 'suklaapatukka', 'soijarouhe', 'taimen', 'tuontikala', 'tomaattikeitto', 'tattari', 'soijajuoma', 'siirappi', 'sienikastike', 'tomaattikastike', 'taateli', 'soijaproteiini', 'siskonmakkarakeitto', 'tomaattimurska', 'tippaleipä', 'tilli', 'ternimaito', 'tahini', 'skyr', 'silakkafilee', 'sienikeitto', 'sianpaisti', 'siankyljys', 'siankinkku', 'tuorepuuro', 'tonnikalapihvi', 'tonnikalapasta', 'tomaattisose', 'tofupihvi', 'tapas', 'suppilovahverokeitto', 'soijapihvi', 'smetana', 'sitruunakastike', 'sipulikeitto', 'sianruho', 'tuulihattu', 'timjami', 'sipulipiirakka', 'torttupohja', 'tomaattisilakka', 'tomaattisalsa', 'tempeh', 'tartarpihvi', 'talkkunapuuro', 'suklaakonvehti', 'sorbetti', 'soijaöljy', 'soijapapu', 'sipulirengas', 'sinisimpukka', 'simpukkakeitto', 'silakkahyytelö', 'siitakesieni', 'sienipiirakka', 'sianpotka', 'sianlihasuikale', 'sianlapa', 'sharon', 'tillikastike', 'tattaripuuro', 'sultsina', 'siankylki', 'suolatikku', 'viini', 'viina', 'voileipä', 'vanukas', 'täytekakku', 'valkosipuli', 'veriohukainen', 'vohveli', 'valkokaali', 'wieninleike', 'vadelma', 'viikuna', 'vesimeloni', 'valkoviini', 'urheilujuoma', 'viineri', 'voileipäkakku', 'viili', 'variksenmarja', 'valkopippuri', 'äidinmaito', 'voisarvi', 'virvoitusjuoma', 'viinietikka', 'vasikanpaisti', 'uuniperuna', 'täysmehu', 'tyrnimarja', 'äidinmaidonkorvike', 'voitaikina', 'täysjyväriisi', 'välipalapatukka', 'viinirypäle', 'väkiviinaetikka', 'voiöljy', 'voileipäpikkelssi', 'virkistysjuoma', 'villirucola', 'viljaporsas', 'viininlehti', 'vihanneskrassi', 'vihanneskeitto', 'vesirinkeli', 'vesikastanja', 'verileipä', 'verigreippi', 'vehnävelli', 'vehnänalkio', 'vehnähiutale', 'vanilliinisokeri', 'vadelmasurvos', 'uunisilakka', 'uuniomena', 'uunihauki', 'vorschmack', 'uunikala', 'urheilujuomatiiviste', 'voirinkeli', 'viininlehtikääryle']
691